### ISSUE TITLE
Azure:Sign In shouldn't fail if at least one tenant authentication succeeds

### ISSUE THREAD

**Issue by onlyann** [Microsoft/vscode-azure-account#24]
Version 0.2.2
VS Code 1.18.1
Windows 10 / Mac OS

When I run the `Azure : Sign In` task, it displays: *Not signed in, sign in first*.
After following the prompts, it opens the browser window and after entering the device code, the message is * You have signed in to the Visual Studio Code application on your device. You may now close this window.*.

However, I remained signed-out in VS Code.
I get the exact same behavior when running `Azure: Sign-In` again.

The account I sign-in with is a company account and I have more than one tenant id associated with my account.

I can successfully sign-in using the [Azure Tools extension](https://marketplace.visualstudio.com/items?itemName=bradygaster.azuretoolsforvscode). One difference is that the extension requires me to setup my tenant id in configuration file.

Let me know if there is anything else I can do to help.

**Comment by chrmarti** [comment]
You should be signed in to all tenants. If you want, you could try debugging the extension and see if you ever get a refresh token: https://github.com/Microsoft/vscode-azure-account/blame/master/src/azure-account.ts#L161

**Comment by onlyann** [comment]
What are the steps to debug a third-party extension ?
I couldn't locate the code in the developer tools.

Al I can see is a console error log : `Error: Acquiring token with refresh token failed` at /OMITTED/.vscode/extensions/ms-vscode.azure-account-0.2.2/out/src/azure-account.js:485:28`

**Comment by chrisdias** [comment]
@onlyann you can clone the repository, open it in VS Code, and then press F5 to run it in debug mode:

``` bash
git clone https://github.com/microsoft/vscode-azure-account
cd vscode-azure-account
npm install
code .
```
Set a breakpoint on https://github.com/Microsoft/vscode-azure-account/blame/master/src/azure-account.ts#L161 and then press `F5` to run the extension. Another instance of VS Code will open and you may get a message about the fact that you are loading the debug version instead of the installed version.

Try to Sign In and you should hit the breakpoint. Let us know what you see.

**Comment by onlyann** [comment]
@chrisdias Much appreciated.

My account is disabled on one of the listed tenants. The obtention of the refresh token fails with `AADSTS50057: User account is disabled`.

Things that would work for my case 
- warn of any failure to obtain the refresh token but continue with other tenants in the list
- have the ability to configure a whitelist/blacklist of tenants

Other than that, what do you think of logging additional information to [the error message](https://github.com/Microsoft/vscode-azure-account/blame/master/src/azure-account.ts#L516) such as `tokenResponse.error_description` ?

**Comment by KacperMucha** [comment]
I'm getting the same outcome. VS Code asks to sign in an infinite loop. I went through provided debugging procedure and I got this error:
Activating extension `ms-vscode.azure-account` failed: Cannot find module 'c:\dev\vscode-azure-account\out\src\extension'

**Comment by onlyann** [comment]
@KacperMucha It seems that the project didn't correctly build when you tried to debug.
I had to first install the TypeScript compiler to get the extension to build.
`npm i typescript -g` . It may also work without the global `-g` option.

**Comment by KacperMucha** [comment]
@onlyann thanks, that worked. Now it doesn't throw that error anymore. Instead I'm getting:
No Azure subscriptions found (are you missing the "azure.tenantId" setting?).
It doesn't reach the breakpoint, and account that I'm using has access to several subscriptions.
Unfortunately I have a little knowledge of JavaScript/TypeScript. I tried to search for tenantId in the project, but found it in many places, so I won't be able to conclude anything probably.

**Comment by onlyann** [comment]
That looks very much like a message from the [Azure Tools extension](https://marketplace.visualstudio.com/items?itemName=bradygaster.azuretoolsforvscode). 
Make sure you are running `Azure: Sign In` (azure account)  and not `Azure: Login` (azure tools).

**Comment by KacperMucha** [comment]
OMG... like a complete noob. :) Now with the correct command I get:
```
Error: Acquiring token with refresh token failed
bootstrap.js:5
	at AzureLoginError.AppInsightsAsyncCorrelatedErrorWrapper (C:\Users\accountname\.vscode\extensions\msazurermtools.azurerm-vscode-tools-0.3.7\node_modules\applicationinsights\out\AutoCollection\CorrelationContextManager.js:172:18)
	at AzureLoginError (c:\dev\vscode-azure-account\out\src\azure-account.js:47:9)
	at c:\dev\vscode-azure-account\out\src\azure-account.js:485:28
	at Request._callback (c:\dev\vscode-azure-account\node_modules\adal-node\lib\util.js:133:7)
	at Request.init.self.callback (c:\dev\vscode-azure-account\node_modules\request\request.js:188:22)
	at ZoneDelegate.invokeTask (C:\Users\accountname\.vscode\extensions\msazurermtools.azurerm-vscode-tools-0.3.7\node_modules\zone.js\dist\zone-node.js:275:35)
	at Zone.runTask (C:\Users\accountname\.vscode\extensions\msazurermtools.azurerm-vscode-tools-0.3.7\node_modules\zone.js\dist\zone-node.js:151:47)
	at Request.ZoneTask.ZoneTask.cancelFn.invoke (C:\Users\accountname\.vscode\extensions\msazurermtools.azurerm-vscode-tools-0.3.7\node_modules\zone.js\dist\zone-node.js:345:33)
	at emitTwo (events.js:106:13)
	at Request.emit (events.js:194:7)
	at Request.<anonymous> (c:\dev\vscode-azure-account\node_modules\request\request.js:1171:10)
	at ZoneDelegate.invokeTask (C:\Users\accountname\.vscode\extensions\msazurermtools.azurerm-vscode-tools-0.3.7\node_modules\zone.js\dist\zone-node.js:275:35)
	at Zone.runTask (C:\Users\accountname\.vscode\extensions\msazurermtools.azurerm-vscode-tools-0.3.7\node_modules\zone.js\dist\zone-node.js:151:47)
	at Request.ZoneTask.ZoneTask.cancelFn.invoke (C:\Users\accountname\.vscode\extensions\msazurermtools.azurerm-vscode-tools-0.3.7\node_modules\zone.js\dist\zone-node.js:345:33)
	at emitOne (events.js:96:13)
	at Request.emit (events.js:191:7)
	at IncomingMessage.<anonymous> (c:\dev\vscode-azure-account\node_modules\request\request.js:1091:12)
	at Object.onceWrapper (events.js:293:19)
	at ZoneDelegate.invokeTask (C:\Users\accountname\.vscode\extensions\msazurermtools.azurerm-vscode-tools-0.3.7\node_modules\zone.js\dist\zone-node.js:275:35)
	at Zone.runTask (C:\Users\accountname\.vscode\extensions\msazurermtools.azurerm-vscode-tools-0.3.7\node_modules\zone.js\dist\zone-node.js:151:47)
	at IncomingMessage.ZoneTask.ZoneTask.cancelFn.invoke (C:\Users\accountname\.vscode\extensions\msazurermtools.azurerm-vscode-tools-0.3.7\node_modules\zone.js\dist\zone-node.js:345:33)
	at emitNone (events.js:91:20)
	at IncomingMessage.emit (events.js:188:7)
	at endReadableNT (_stream_readable.js:975:12)
	at ZoneDelegate.invokeTask (C:\Users\accountname\.vscode\extensions\msazurermtools.azurerm-vscode-tools-0.3.7\node_modules\zone.js\dist\zone-node.js:275:35)
	at Zone.runTask (C:\Users\accountname\.vscode\extensions\msazurermtools.azurerm-vscode-tools-0.3.7\node_modules\zone.js\dist\zone-node.js:151:4
```
I think that it's work mentioning that I'm using an account that has double MFA. Because it has access to two tenants and both of them have MFA enabled.

**Comment by onlyann** [comment]
Can you put a breakpoint at `https://github.com/Microsoft/vscode-azure-account/blame/master/src/azure-account.ts#L516` ?
When it reaches it, have a look at the value of `tokenResponse.error_description` from the *Watch* or *Locals* window as it may have additional error information.

**Comment by KacperMucha** [comment]
"AADSTS50076: Due to a configuration change made by your administrator, or because you moved to a new location, you must use multi-factor authentication to access '<id>'.
But the id that is there does not to point any subscription or tenant id.

**Comment by chrmarti** [comment]
(Back from long vacation.)

@onlyann Thanks for the analysis. Could you check if the disabled tenant is somehow flagged as such in the tenant object for it in: https://github.com/Microsoft/vscode-azure-account/blob/master/src/azure-account.ts#L530

@KacperMucha Is this still a problem? Could you open a new issue to track it?

**Comment by onlyann** [comment]
@chrmarti I can't reproduce anymore as the tenant has been re-enabled. I'll post my findings if/when I can.

**Comment by chrmarti** [comment]
Will fix this by logging and continuing with the other tenants for now.

**Comment by VickiFu** [comment]
I have exact same issue. My account works well in Windows OS, but Mac OS. it never get through the auth. I had reinstall everything. it still doesnt work. i had the debug setting. 
The error is "command 'azureStorage.refresh' not found"

**Comment by chrmarti** [comment]
@VickiFu Please check if there is anything in VS Code's console (Help > Toggle Developer Tools).
