### ISSUE TITLE
"You appear to be offline. Please check your network connection."

### ISSUE THREAD

**Issue by amosbaker** [microsoft/vscode-azure-account#245]
Issue Type: <b>Bug</b>

Any attempt to sign in to Azure via this extension within WSL results in failure.

Extension version: 0.9.4
VS Code version: Code 1.52.1 (ea3859d4ba2f3e577a159bc91e3074c5d85c0523, 2020-12-16T16:34:46.910Z)
OS version: Windows_NT x64 10.0.18363
Remote OS version: Linux x64 4.4.0-18362-Microsoft

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-8650U CPU @ 1.90GHz (8 x 2112)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>opengl: enabled_on<br>protected_video_decode: enabled<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|15.85GB (1.41GB free)|
|Process Argv|--folder-uri=vscode-remote://wsl+Ubuntu-18.04/mnt/c/funcenvtest --remote=wsl+Ubuntu-18.04 --crash-reporter-id 687281fe-b5df-40c2-aaa6-3563267e3b37|
|Screen Reader|no|
|VM|0%|

|Item|Value|
|---|---|
|Remote|WSL: Ubuntu-18.04|
|OS|Linux x64 4.4.0-18362-Microsoft|
|CPUs|Intel(R) Core(TM) i7-8650U CPU @ 1.90GHz (8 x 2112)|
|Memory (System)|15.85GB (1.41GB free)|
|VM|0%|
</details>

**Comment by nturinski** [comment]
Could you try updating the most recent version of the extension (0.9.8) and VS Code (WSL) and trying this again?

**Comment by amosbaker** [comment]
I updated VS Code and attempted to relaunch to update the extension and now I get this when I try to launch
```
$ code
Updating VS Code Server to version 507ce72a4466fbb27b715c3722558bb15afa9f48
Removing previous installation...
Installing VS Code Server for x64 (507ce72a4466fbb27b715c3722558bb15afa9f48)
Downloading: 100%
Failed
--2021-06-30 10:56:55--  https://update.code.visualstudio.com/commit:507ce72a4466fbb27b715c3722558bb15afa9f48/server-linux-x64/stable
Resolving update.code.visualstudio.com (update.code.visualstudio.com)... failed: Temporary failure in name resolution.
wget: unable to resolve host address ‘update.code.visualstudio.com’
ERROR: Failed to download https://update.code.visualstudio.com/commit:507ce72a4466fbb27b715c3722558bb15afa9f48/server-linux-x64/stable to /home/amos/.vscode-server/bin/507ce72a4466fbb27b715c3722558bb15afa9f48-1625064874.tar.gz
```

I did verify my WSL instance is properly connected to the internets.
```
$ curl www.microsoft.com
<html><head><title>Microsoft Corporation</title><meta http-equiv="X-UA-Compatible" content="IE=EmulateIE7"></meta><meta http-equiv="Content-Type" content="text/html; charset=utf-8"></meta><meta name="SearchTitle" content="Microsoft.com" scheme=""></meta><meta name="Description" content="Get product information, support, and news from Microsoft." scheme=""></meta><meta name="Title" content="Microsoft.com Home Page" scheme=""></meta><meta name="Keywords" content="Microsoft, product, support, help, training, Office, Windows, software, download, trial, preview, demo,  business, security, update, free, computer, PC, server, search, download, install, news" scheme=""></meta><meta name="SearchDescription" content="Microsoft.com Homepage" scheme=""></meta></head><body><p>Your current User-Agent string appears to be from an automated process, if this is incorrect, please click this link:<a href="http://www.microsoft.com/en/us/default.aspx?redir=true">United States English Microsoft Homepage</a></p></body></html>
```

**Comment by amosbaker** [comment]
Also, I am not behind a proxy. 
```
$ env | grep -i prox
$
```

**Comment by wwlorey** [comment]
> I updated VS Code and attempted to relaunch to update the extension and now I get this when I try to launch

I would bring this issue up with the VS Code team [here](https://github.com/microsoft/vscode/issues) if you're still running into it. Once that gets figured out we can address the "you appear to be offline" error coming from the Account Extension.

**Comment by wwlorey** [comment]
Closing since this appears to be an issue with your network.

**Comment by nor-ko** [comment]
I got same issue with spesific proxy password including `%%`.

Extension Version: Azure Account v0.9.11
VSCode Version: 1.63.2 (system setup)
commit: 899d46d82c4c95423fb7e10e68eba52050e30ba3
Date : 2021-12-15T09:40:02.816Z
Electron: 13.5.2
Chromium: 91.0.4472.164
Node.js: 14.16.0
V8: 9.1.269.39-electron.0
OS: Windows_NT x64 10.0.19043

In settings.json, I set `http.proxy: http://myuser:pypasssurfix%%@proxyhost:proxyport`.

log (extension host) says...

```text
[2022-01-27 09:56:21.749] [exthost] [debug] ProxyResolver#resolveProxy settings https://login.microsoftonline.com/ PROXY myuser:mypasssurfix%%@proxyhost:proxyport 
Error: Error for stack trace
    at resolveProxy (c:\Program Files\Microsoft VS Code\resources\app\node_modules.asar\vscode-proxy-agent\out\index.js:105:69)
    at c:\Program Files\Microsoft VS Code\resources\app\node_modules.asar\vscode-proxy-agent\out\index.js:293:77
    at new Promise (<anonymous>)
    at _PacProxyAgent.resolveP (c:\Program Files\Microsoft VS Code\resources\app\node_modules.asar\vscode-proxy-agent\out\index.js:293:54)
    at _PacProxyAgent.<anonymous> (c:\Program Files\Microsoft VS Code\resources\app\node_modules.asar\vscode-proxy-agent\out\agent.js:71:37)
    at Generator.next (<anonymous>)
    at c:\Program Files\Microsoft VS Code\resources\app\node_modules.asar\vscode-proxy-agent\out\agent.js:8:71
    at new Promise (<anonymous>)
    at __awaiter (c:\Program Files\Microsoft VS Code\resources\app\node_modules.asar\vscode-proxy-agent\out\agent.js:4:12)
    at _PacProxyAgent.callback (c:\Program Files\Microsoft VS Code\resources\app\node_modules.asar\vscode-proxy-agent\out\agent.js:53:16)
    at _PacProxyAgent.addRequest (c:\Program Files\Microsoft VS Code\resources\app\node_modules.asar\vscode-proxy-agent\node_modules\agent-base\dist\src\index.js:184:38)
    at new ClientRequest (_http_client.js:306:16)
    at request (https.js:313:10)
    at Object.patched (c:\Program Files\Microsoft VS Code\resources\app\node_modules.asar\vscode-proxy-agent\out\index.js:297:24)
    at Object.i.request (c:\Users\10379476\.vscode\extensions\ms-vscode.azure-account-0.9.11\dist\extension.js:646:101276)
    at Object.i.request.<computed>.i.request [as request] (c:\Users\10379476\.vscode\extensions\ms-vscode.azure-account-0.9.11\dist\extension.js:669:189472)
    at Object.i.get (c:\Users\10379476\.vscode\extensions\ms-vscode.azure-account-0.9.11\dist\extension.js:669:189640)
    at c:\Users\10379476\.vscode\extensions\ms-vscode.azure-account-0.9.11\dist\extension.js:881:7711
    at new Promise (<anonymous>)
    at c:\Users\10379476\.vscode\extensions\ms-vscode.azure-account-0.9.11\dist\extension.js:881:7624
    at Generator.next (<anonymous>)
    at c:\Users\10379476\.vscode\extensions\ms-vscode.azure-account-0.9.11\dist\extension.js:881:1120
    at new Promise (<anonymous>)
    at n (c:\Users\10379476\.vscode\extensions\ms-vscode.azure-account-0.9.11\dist\extension.js:881:865)
    at W (c:\Users\10379476\.vscode\extensions\ms-vscode.azure-account-0.9.11\dist\extension.js:881:7573)
    at c:\Users\10379476\.vscode\extensions\ms-vscode.azure-account-0.9.11\dist\extension.js:881:7533
    at Generator.next (<anonymous>)
    at a (c:\Users\10379476\.vscode\extensions\ms-vscode.azure-account-0.9.11\dist\extension.js:881:922)
```

It looks come from vscode-proxy-agent.
I also try to sign in for account sync with microsoft account, It also failed.

Then, I change my password without `%%`, sign in for account sync work normally.
But for the Azure account, raise another error `URI malformed`.
