### ISSUE TITLE
Cannot activate the 'Azure Virtual Machines' extension because it depends on the 'Azure Account' extension, which is not loaded

### ISSUE THREAD

**Issue by yelkarama** [microsoft/vscode-azure-account#249]
After clickcing on Azure Icon in VSCode (WSL), I get this error:

`Cannot activate the 'Azure Virtual Machines' extension because it depends on the 'Azure Account' extension, which is not loaded. Would you like to reload the window to load the extension?`

All other tabs (App service, Functions, Resources Groups, Storage and Databases) show Azure resources as expected. 

This error does not occur when using VSCode locally (without  WSL).

Here is the detailled error message from the Developer Tools Window:

`workbench.desktop.main.js:60 [Extension Host] Error: Get Token request returned http error: 400 and server response: {"error":"interaction_required","error_description":"AADSTS50076: Due to a configuration change made by your administrator, or because you moved to a new location, you must use multi-factor authentication to access '797f4846-ba00-4fd7-ba43-dac1f8f63013'.\r\nTrace ID: 05e18b24-d83e-4d1b-98e9-40bdfaec3d00\r\nCorrelation ID: e6d7718b-a2df-4490-9807-11f00ffc1da7\r\nTimestamp: 2021-02-16 00:27:44Z","error_codes":[50076],"timestamp":"2021-02-16 00:27:44Z","trace_id":"05e18b24-d83e-4d1b-98e9-40bdfaec3d00","correlation_id":"e6d7718b-a2df-4490-9807-11f00ffc1da7","error_uri":"https://login.microsoftonline.com/error?code=50076","suberror":"basic_action"}	at s.createError (/home/younes/.vscode-server-insiders/extensions/ms-vscode.azure-account-0.9.6/dist/extension.js:16:58035)	at B._callback (/home/younes/.vscode-server-insiders/extensions/ms-vscode.azure-account-0.9.6/dist/extension.js:16:228419)	at B.t._callback.t.callback.t.callback (/home/younes/.vscode-server-insiders/extensions/ms-vscode.azure-account-0.9.6/dist/extension.js:202:5500)	at B.emit (events.js:315:20)	at B.EventEmitter.emit (domain.js:483:12)	at B.<anonymous> (/home/younes/.vscode-server-insiders/extensions/ms-vscode.azure-account-0.9.6/dist/extension.js:202:18360)	at B.emit (events.js:315:20)	at B.EventEmitter.emit (domain.js:483:12)	at IncomingMessage.<anonymous> (/home/younes/.vscode-server-insiders/extensions/ms-vscode.azure-account-0.9.6/dist/extension.js:202:17192)	at Object.onceWrapper (events.js:421:28)	at IncomingMessage.emit (events.js:327:22)	at IncomingMessage.EventEmitter.emit (domain.js:483:12)	at endReadableNT (_stream_readable.js:1220:12)	at processTicksAndRejections (internal/process/task_queues.js:84:21)
b @ workbench.desktop.main.js:60`

**Comment by fle108** [comment]
same problem here. only with wsl

**Comment by neg2led** [comment]
Seeing this issue as well; the error points to something MFA-related, but I did sign in using MFA & it only seems to be VMs that are affected.

**Comment by garymm** [comment]
The extension works on local workspaces but I see this same error message on a remote (SSH) workspace. Perhaps because the Azure Virtual Machines extension runs locally, while the Account extension runs on the remote host?
