### ISSUE TITLE
Azure Sign in: Unable to get local issuer certificate

### ISSUE THREAD

**Issue by oozut** [microsoft/vscode-azure-account#269]
I am trying to connect to a Azure Machine Learning compute node but I have some trouble connecting to my azure account using the ``Azure: Sign In'' method.

VS Code version:
Version: 1.56.1 (user setup)
Commit: e713fe9b05fc24facbec8f34fb1017133858842b
Date: 2021-05-06T10:42:59.088Z
Electron: 12.0.4
Chrome: 89.0.4389.114
Node.js: 14.16.0
V8: 8.9.255.24-electron.0
OS: Windows_NT ia32 6.1.7601

Azure Account Version: 0.9.8

The setting for Visual Studio code for proxy and azure are:
```
    "azure.cloud": "AzureCloud",
    "http.proxyStrictSSL": true,
    "http.systemCertificates": true
```

I get the following error from chrome console:
![image](https://user-images.githubusercontent.com/22704625/118012303-cfc8e980-b348-11eb-868d-312d76837a20.png)

and the following on the trace from VS Code:
```
[2021-05-12 17:17:38.925] [exthost] [trace] ExtHostCommands#$executeContributedCommand azure-account.login
[2021-05-12 17:17:38.927] [exthost] [debug] ProxyResolver#resolveProxy cached https://login.microsoftonline.com/ DIRECT 
Error: Error for stack trace
	at resolveProxy (c:\Users\<username>\AppData\Local\Programs\Microsoft VS Code\resources\app\node_modules.asar\vscode-proxy-agent\out\index.js:105:69)
	at c:\Users\<username>\AppData\Local\Programs\Microsoft VS Code\resources\app\node_modules.asar\vscode-proxy-agent\out\index.js:293:77
	at new Promise (<anonymous>)
	at _PacProxyAgent.resolveP [as resolver] (c:\Users\<username>\AppData\Local\Programs\Microsoft VS Code\resources\app\node_modules.asar\vscode-proxy-agent\out\index.js:293:54)
	at _PacProxyAgent.<anonymous> (c:\Users\<username>\AppData\Local\Programs\Microsoft VS Code\resources\app\node_modules.asar\vscode-proxy-agent\out\agent.js:71:37)
	at Generator.next (<anonymous>)
	at c:\Users\<username>\AppData\Local\Programs\Microsoft VS Code\resources\app\node_modules.asar\vscode-proxy-agent\out\agent.js:8:71
	at new Promise (<anonymous>)
	at __awaiter (c:\Users\<username>\AppData\Local\Programs\Microsoft VS Code\resources\app\node_modules.asar\vscode-proxy-agent\out\agent.js:4:12)
	at _PacProxyAgent.callback (c:\Users\<username>\AppData\Local\Programs\Microsoft VS Code\resources\app\node_modules.asar\vscode-proxy-agent\out\agent.js:53:16)
	at _PacProxyAgent.addRequest (c:\Users\<username>\AppData\Local\Programs\Microsoft VS Code\resources\app\node_modules.asar\vscode-proxy-agent\node_modules\agent-base\dist\src\index.js:184:38)
	at new ClientRequest (_http_client.js:306:16)
	at request (https.js:313:10)
	at Object.patched (c:\Users\<username>\AppData\Local\Programs\Microsoft VS Code\resources\app\node_modules.asar\vscode-proxy-agent\out\index.js:297:24)
	at Object.i.request (c:\Users\<username>\.vscode\extensions\ms-vscode.azure-account-0.9.8\dist\extension.js:211:101276)
	at Object.i.request.<computed>.i.request (c:\Users\<username>\.vscode\extensions\ms-vscode.azure-account-0.9.8\dist\extension.js:234:48887)
	at Object.i.get (c:\Users\<username>\.vscode\extensions\ms-vscode.azure-account-0.9.8\dist\extension.js:234:49055)
	at c:\Users\<username>\.vscode\extensions\ms-vscode.azure-account-0.9.8\dist\extension.js:446:7700
	at new Promise (<anonymous>)
	at c:\Users\<username>\.vscode\extensions\ms-vscode.azure-account-0.9.8\dist\extension.js:446:7613
	at Generator.next (<anonymous>)
	at c:\Users\<username>\.vscode\extensions\ms-vscode.azure-account-0.9.8\dist\extension.js:446:1120
	at new Promise (<anonymous>)
	at n (c:\Users\<username>\.vscode\extensions\ms-vscode.azure-account-0.9.8\dist\extension.js:446:865)
	at W (c:\Users\<username>\.vscode\extensions\ms-vscode.azure-account-0.9.8\dist\extension.js:446:7562)
	at c:\Users\<username>\.vscode\extensions\ms-vscode.azure-account-0.9.8\dist\extension.js:446:7430
	at Generator.next (<anonymous>)
	at c:\Users\<username>\.vscode\extensions\ms-vscode.azure-account-0.9.8\dist\extension.js:446:1120
	at new Promise (<anonymous>)
	at n (c:\Users\<username>\.vscode\extensions\ms-vscode.azure-account-0.9.8\dist\extension.js:446:865)
	at V (c:\Users\<username>\.vscode\extensions\ms-vscode.azure-account-0.9.8\dist\extension.js:446:7390)
	at t.AzureLoginHelper.<anonymous> (c:\Users\<username>\.vscode\extensions\ms-vscode.azure-account-0.9.8\dist\extension.js:446:10626)
	at Generator.next (<anonymous>)
	at a (c:\Users\<username>\.vscode\extensions\ms-vscode.azure-account-0.9.8\dist\extension.js:446:922)
	at processTicksAndRejections (internal/process/task_queues.js:93:5)
[2021-05-12 17:17:39.064] [exthost] [debug] ProxyResolver#resolveProxy cached https://vscode-redirect.azurewebsites.net/?state=3333,cccc PROXY [redacted_proxy] 
Error: Error for stack trace
	at resolveProxy (c:\Users\<username>\AppData\Local\Programs\Microsoft VS Code\resources\app\node_modules.asar\vscode-proxy-agent\out\index.js:105:69)
	at c:\Users\<username>\AppData\Local\Programs\Microsoft VS Code\resources\app\node_modules.asar\vscode-proxy-agent\out\index.js:293:77
	at new Promise (<anonymous>)
	at _PacProxyAgent.resolveP [as resolver] (c:\Users\<username>\AppData\Local\Programs\Microsoft VS Code\resources\app\node_modules.asar\vscode-proxy-agent\out\index.js:293:54)
	at _PacProxyAgent.<anonymous> (c:\Users\<username>\AppData\Local\Programs\Microsoft VS Code\resources\app\node_modules.asar\vscode-proxy-agent\out\agent.js:71:37)
	at Generator.next (<anonymous>)
	at c:\Users\<username>\AppData\Local\Programs\Microsoft VS Code\resources\app\node_modules.asar\vscode-proxy-agent\out\agent.js:8:71
	at new Promise (<anonymous>)
	at __awaiter (c:\Users\<username>\AppData\Local\Programs\Microsoft VS Code\resources\app\node_modules.asar\vscode-proxy-agent\out\agent.js:4:12)
	at _PacProxyAgent.callback (c:\Users\<username>\AppData\Local\Programs\Microsoft VS Code\resources\app\node_modules.asar\vscode-proxy-agent\out\agent.js:53:16)
	at _PacProxyAgent.addRequest (c:\Users\<username>\AppData\Local\Programs\Microsoft VS Code\resources\app\node_modules.asar\vscode-proxy-agent\node_modules\agent-base\dist\src\index.js:184:38)
	at new ClientRequest (_http_client.js:306:16)
	at request (https.js:313:10)
	at Object.patched (c:\Users\<username>\AppData\Local\Programs\Microsoft VS Code\resources\app\node_modules.asar\vscode-proxy-agent\out\index.js:297:24)
	at Object.i.request (c:\Users\<username>\.vscode\extensions\ms-vscode.azure-account-0.9.8\dist\extension.js:211:101276)
	at Object.i.request.<computed>.i.request (c:\Users\<username>\.vscode\extensions\ms-vscode.azure-account-0.9.8\dist\extension.js:234:48887)
	at Object.i.get (c:\Users\<username>\.vscode\extensions\ms-vscode.azure-account-0.9.8\dist\extension.js:234:49055)
	at c:\Users\<username>\.vscode\extensions\ms-vscode.azure-account-0.9.8\dist\extension.js:446:40563
	at new Promise (<anonymous>)
	at Object.<anonymous> (c:\Users\<username>\.vscode\extensions\ms-vscode.azure-account-0.9.8\dist\extension.js:446:40536)
	at Generator.next (<anonymous>)
	at c:\Users\<username>\.vscode\extensions\ms-vscode.azure-account-0.9.8\dist\extension.js:446:39951
	at new Promise (<anonymous>)
	at n (c:\Users\<username>\.vscode\extensions\ms-vscode.azure-account-0.9.8\dist\extension.js:446:39696)
	at Object.t.checkRedirectServer (c:\Users\<username>\.vscode\extensions\ms-vscode.azure-account-0.9.8\dist\extension.js:446:40474)
	at t.AzureLoginHelper.<anonymous> (c:\Users\<username>\.vscode\extensions\ms-vscode.azure-account-0.9.8\dist\extension.js:446:11059)
	at Generator.next (<anonymous>)
	at a (c:\Users\<username>\.vscode\extensions\ms-vscode.azure-account-0.9.8\dist\extension.js:446:922)
	at processTicksAndRejections (internal/process/task_queues.js:93:5)
[2021-05-12 17:17:39.625] [exthost] [debug] ProxyResolver#resolveProxy cached https://login.microsoftonline.com/common/oauth2/token?api-version=1.0 DIRECT 
Error: Error for stack trace
	at resolveProxy (c:\Users\<username>\AppData\Local\Programs\Microsoft VS Code\resources\app\node_modules.asar\vscode-proxy-agent\out\index.js:105:69)
	at c:\Users\<username>\AppData\Local\Programs\Microsoft VS Code\resources\app\node_modules.asar\vscode-proxy-agent\out\index.js:293:77
	at new Promise (<anonymous>)
	at _PacProxyAgent.resolveP [as resolver] (c:\Users\<username>\AppData\Local\Programs\Microsoft VS Code\resources\app\node_modules.asar\vscode-proxy-agent\out\index.js:293:54)
	at _PacProxyAgent.<anonymous> (c:\Users\<username>\AppData\Local\Programs\Microsoft VS Code\resources\app\node_modules.asar\vscode-proxy-agent\out\agent.js:71:37)
	at Generator.next (<anonymous>)
	at c:\Users\<username>\AppData\Local\Programs\Microsoft VS Code\resources\app\node_modules.asar\vscode-proxy-agent\out\agent.js:8:71
	at new Promise (<anonymous>)
	at __awaiter (c:\Users\<username>\AppData\Local\Programs\Microsoft VS Code\resources\app\node_modules.asar\vscode-proxy-agent\out\agent.js:4:12)
	at _PacProxyAgent.callback (c:\Users\<username>\AppData\Local\Programs\Microsoft VS Code\resources\app\node_modules.asar\vscode-proxy-agent\out\agent.js:53:16)
	at _PacProxyAgent.addRequest (c:\Users\<username>\AppData\Local\Programs\Microsoft VS Code\resources\app\node_modules.asar\vscode-proxy-agent\node_modules\agent-base\dist\src\index.js:184:38)
	at new ClientRequest (_http_client.js:306:16)
	at request (https.js:313:10)
	at Object.patched (c:\Users\<username>\AppData\Local\Programs\Microsoft VS Code\resources\app\node_modules.asar\vscode-proxy-agent\out\index.js:297:24)
	at Object.i.request (c:\Users\<username>\.vscode\extensions\ms-vscode.azure-account-0.9.8\dist\extension.js:211:101276)
	at Object.i.request.<computed>.i.request (c:\Users\<username>\.vscode\extensions\ms-vscode.azure-account-0.9.8\dist\extension.js:234:48887)
	at B.start (c:\Users\<username>\.vscode\extensions\ms-vscode.azure-account-0.9.8\dist\extension.js:265:11770)
	at B.write (c:\Users\<username>\.vscode\extensions\ms-vscode.azure-account-0.9.8\dist\extension.js:265:22017)
	at e (c:\Users\<username>\.vscode\extensions\ms-vscode.azure-account-0.9.8\dist\extension.js:265:9649)
	at Immediate._onImmediate (c:\Users\<username>\.vscode\extensions\ms-vscode.azure-account-0.9.8\dist\extension.js:265:10149)
	at processImmediate (internal/timers.js:461:21)
[2021-05-12 17:17:39.851] [exthost] [debug] ProxyResolver#resolveProxy cached https://login.microsoftonline.com/common/oauth2/devicecode?api-version=1.0 DIRECT 
Error: Error for stack trace
	at resolveProxy (c:\Users\<username>\AppData\Local\Programs\Microsoft VS Code\resources\app\node_modules.asar\vscode-proxy-agent\out\index.js:105:69)
	at c:\Users\<username>\AppData\Local\Programs\Microsoft VS Code\resources\app\node_modules.asar\vscode-proxy-agent\out\index.js:293:77
	at new Promise (<anonymous>)
	at _PacProxyAgent.resolveP [as resolver] (c:\Users\<username>\AppData\Local\Programs\Microsoft VS Code\resources\app\node_modules.asar\vscode-proxy-agent\out\index.js:293:54)
	at _PacProxyAgent.<anonymous> (c:\Users\<username>\AppData\Local\Programs\Microsoft VS Code\resources\app\node_modules.asar\vscode-proxy-agent\out\agent.js:71:37)
	at Generator.next (<anonymous>)
	at c:\Users\<username>\AppData\Local\Programs\Microsoft VS Code\resources\app\node_modules.asar\vscode-proxy-agent\out\agent.js:8:71
	at new Promise (<anonymous>)
	at __awaiter (c:\Users\<username>\AppData\Local\Programs\Microsoft VS Code\resources\app\node_modules.asar\vscode-proxy-agent\out\agent.js:4:12)
	at _PacProxyAgent.callback (c:\Users\<username>\AppData\Local\Programs\Microsoft VS Code\resources\app\node_modules.asar\vscode-proxy-agent\out\agent.js:53:16)
	at _PacProxyAgent.addRequest (c:\Users\<username>\AppData\Local\Programs\Microsoft VS Code\resources\app\node_modules.asar\vscode-proxy-agent\node_modules\agent-base\dist\src\index.js:184:38)
	at new ClientRequest (_http_client.js:306:16)
	at request (https.js:313:10)
	at Object.patched (c:\Users\<username>\AppData\Local\Programs\Microsoft VS Code\resources\app\node_modules.asar\vscode-proxy-agent\out\index.js:297:24)
	at Object.i.request (c:\Users\<username>\.vscode\extensions\ms-vscode.azure-account-0.9.8\dist\extension.js:211:101276)
	at Object.i.request.<computed>.i.request (c:\Users\<username>\.vscode\extensions\ms-vscode.azure-account-0.9.8\dist\extension.js:234:48887)
	at B.start (c:\Users\<username>\.vscode\extensions\ms-vscode.azure-account-0.9.8\dist\extension.js:265:11770)
	at B.write (c:\Users\<username>\.vscode\extensions\ms-vscode.azure-account-0.9.8\dist\extension.js:265:22017)
	at e (c:\Users\<username>\.vscode\extensions\ms-vscode.azure-account-0.9.8\dist\extension.js:265:9649)
	at Immediate._onImmediate (c:\Users\<username>\.vscode\extensions\ms-vscode.azure-account-0.9.8\dist\extension.js:265:10149)
	at processImmediate (internal/timers.js:461:21)
[2021-05-12 17:17:40.054] [exthost] [debug] ProxyResolver#resolveProxy cached https://login.microsoftonline.com/common/oauth2/token?api-version=1.0 DIRECT 
Error: Error for stack trace
	at resolveProxy (c:\Users\<username>\AppData\Local\Programs\Microsoft VS Code\resources\app\node_modules.asar\vscode-proxy-agent\out\index.js:105:69)
	at c:\Users\<username>\AppData\Local\Programs\Microsoft VS Code\resources\app\node_modules.asar\vscode-proxy-agent\out\index.js:293:77
	at new Promise (<anonymous>)
	at _PacProxyAgent.resolveP [as resolver] (c:\Users\<username>\AppData\Local\Programs\Microsoft VS Code\resources\app\node_modules.asar\vscode-proxy-agent\out\index.js:293:54)
	at _PacProxyAgent.<anonymous> (c:\Users\<username>\AppData\Local\Programs\Microsoft VS Code\resources\app\node_modules.asar\vscode-proxy-agent\out\agent.js:71:37)
	at Generator.next (<anonymous>)
	at c:\Users\<username>\AppData\Local\Programs\Microsoft VS Code\resources\app\node_modules.asar\vscode-proxy-agent\out\agent.js:8:71
	at new Promise (<anonymous>)
	at __awaiter (c:\Users\<username>\AppData\Local\Programs\Microsoft VS Code\resources\app\node_modules.asar\vscode-proxy-agent\out\agent.js:4:12)
	at _PacProxyAgent.callback (c:\Users\<username>\AppData\Local\Programs\Microsoft VS Code\resources\app\node_modules.asar\vscode-proxy-agent\out\agent.js:53:16)
	at _PacProxyAgent.addRequest (c:\Users\<username>\AppData\Local\Programs\Microsoft VS Code\resources\app\node_modules.asar\vscode-proxy-agent\node_modules\agent-base\dist\src\index.js:184:38)
	at new ClientRequest (_http_client.js:306:16)
	at request (https.js:313:10)
	at Object.patched (c:\Users\<username>\AppData\Local\Programs\Microsoft VS Code\resources\app\node_modules.asar\vscode-proxy-agent\out\index.js:297:24)
	at Object.i.request (c:\Users\<username>\.vscode\extensions\ms-vscode.azure-account-0.9.8\dist\extension.js:211:101276)
	at Object.i.request.<computed>.i.request (c:\Users\<username>\.vscode\extensions\ms-vscode.azure-account-0.9.8\dist\extension.js:234:48887)
	at B.start (c:\Users\<username>\.vscode\extensions\ms-vscode.azure-account-0.9.8\dist\extension.js:265:11770)
	at B.write (c:\Users\<username>\.vscode\extensions\ms-vscode.azure-account-0.9.8\dist\extension.js:265:22017)
	at e (c:\Users\<username>\.vscode\extensions\ms-vscode.azure-account-0.9.8\dist\extension.js:265:9649)
	at Immediate._onImmediate (c:\Users\<username>\.vscode\extensions\ms-vscode.azure-account-0.9.8\dist\extension.js:265:10149)
	at processImmediate (internal/timers.js:461:21)
[2021-05-12 17:17:44.759] [exthost] [debug] ProxyResolver#resolveProxy cached https://login.microsoftonline.com/common/oauth2/token?api-version=1.0 DIRECT 
Error: Error for stack trace
	at resolveProxy (c:\Users\<username>\AppData\Local\Programs\Microsoft VS Code\resources\app\node_modules.asar\vscode-proxy-agent\out\index.js:105:69)
	at c:\Users\<username>\AppData\Local\Programs\Microsoft VS Code\resources\app\node_modules.asar\vscode-proxy-agent\out\index.js:293:77
	at new Promise (<anonymous>)
	at _PacProxyAgent.resolveP [as resolver] (c:\Users\<username>\AppData\Local\Programs\Microsoft VS Code\resources\app\node_modules.asar\vscode-proxy-agent\out\index.js:293:54)
	at _PacProxyAgent.<anonymous> (c:\Users\<username>\AppData\Local\Programs\Microsoft VS Code\resources\app\node_modules.asar\vscode-proxy-agent\out\agent.js:71:37)
	at Generator.next (<anonymous>)
	at c:\Users\<username>\AppData\Local\Programs\Microsoft VS Code\resources\app\node_modules.asar\vscode-proxy-agent\out\agent.js:8:71
	at new Promise (<anonymous>)
	at __awaiter (c:\Users\<username>\AppData\Local\Programs\Microsoft VS Code\resources\app\node_modules.asar\vscode-proxy-agent\out\agent.js:4:12)
	at _PacProxyAgent.callback (c:\Users\<username>\AppData\Local\Programs\Microsoft VS Code\resources\app\node_modules.asar\vscode-proxy-agent\out\agent.js:53:16)
	at _PacProxyAgent.addRequest (c:\Users\<username>\AppData\Local\Programs\Microsoft VS Code\resources\app\node_modules.asar\vscode-proxy-agent\node_modules\agent-base\dist\src\index.js:184:38)
	at new ClientRequest (_http_client.js:306:16)
	at request (https.js:313:10)
	at Object.patched (c:\Users\<username>\AppData\Local\Programs\Microsoft VS Code\resources\app\node_modules.asar\vscode-proxy-agent\out\index.js:297:24)
	at Object.i.request (c:\Users\<username>\.vscode\extensions\ms-vscode.azure-account-0.9.8\dist\extension.js:211:101276)
	at Object.i.request.<computed>.i.request (c:\Users\<username>\.vscode\extensions\ms-vscode.azure-account-0.9.8\dist\extension.js:234:48887)
	at B.start (c:\Users\<username>\.vscode\extensions\ms-vscode.azure-account-0.9.8\dist\extension.js:265:11770)
	at B.write (c:\Users\<username>\.vscode\extensions\ms-vscode.azure-account-0.9.8\dist\extension.js:265:22017)
	at e (c:\Users\<username>\.vscode\extensions\ms-vscode.azure-account-0.9.8\dist\extension.js:265:9649)
	at Immediate._onImmediate (c:\Users\<username>\.vscode\extensions\ms-vscode.azure-account-0.9.8\dist\extension.js:265:10149)
	at processImmediate (internal/timers.js:461:21)
[2021-05-12 17:17:45.227] [exthost] [debug] ProxyResolver#resolveProxy cached https://login.microsoftonline.com/common/oauth2/token?api-version=1.0 DIRECT 
Error: Error for stack trace
	at resolveProxy (c:\Users\<username>\AppData\Local\Programs\Microsoft VS Code\resources\app\node_modules.asar\vscode-proxy-agent\out\index.js:105:69)
	at c:\Users\<username>\AppData\Local\Programs\Microsoft VS Code\resources\app\node_modules.asar\vscode-proxy-agent\out\index.js:293:77
	at new Promise (<anonymous>)
	at _PacProxyAgent.resolveP [as resolver] (c:\Users\<username>\AppData\Local\Programs\Microsoft VS Code\resources\app\node_modules.asar\vscode-proxy-agent\out\index.js:293:54)
	at _PacProxyAgent.<anonymous> (c:\Users\<username>\AppData\Local\Programs\Microsoft VS Code\resources\app\node_modules.asar\vscode-proxy-agent\out\agent.js:71:37)
	at Generator.next (<anonymous>)
	at c:\Users\<username>\AppData\Local\Programs\Microsoft VS Code\resources\app\node_modules.asar\vscode-proxy-agent\out\agent.js:8:71
	at new Promise (<anonymous>)
	at __awaiter (c:\Users\<username>\AppData\Local\Programs\Microsoft VS Code\resources\app\node_modules.asar\vscode-proxy-agent\out\agent.js:4:12)
	at _PacProxyAgent.callback (c:\Users\<username>\AppData\Local\Programs\Microsoft VS Code\resources\app\node_modules.asar\vscode-proxy-agent\out\agent.js:53:16)
	at _PacProxyAgent.addRequest (c:\Users\<username>\AppData\Local\Programs\Microsoft VS Code\resources\app\node_modules.asar\vscode-proxy-agent\node_modules\agent-base\dist\src\index.js:184:38)
	at new ClientRequest (_http_client.js:306:16)
	at request (https.js:313:10)
	at Object.patched (c:\Users\<username>\AppData\Local\Programs\Microsoft VS Code\resources\app\node_modules.asar\vscode-proxy-agent\out\index.js:297:24)
	at Object.i.request (c:\Users\<username>\.vscode\extensions\ms-vscode.azure-account-0.9.8\dist\extension.js:211:101276)
	at Object.i.request.<computed>.i.request (c:\Users\<username>\.vscode\extensions\ms-vscode.azure-account-0.9.8\dist\extension.js:234:48887)
	at B.start (c:\Users\<username>\.vscode\extensions\ms-vscode.azure-account-0.9.8\dist\extension.js:265:11770)
	at B.write (c:\Users\<username>\.vscode\extensions\ms-vscode.azure-account-0.9.8\dist\extension.js:265:22017)
	at e (c:\Users\<username>\.vscode\extensions\ms-vscode.azure-account-0.9.8\dist\extension.js:265:9649)
	at Immediate._onImmediate (c:\Users\<username>\.vscode\extensions\ms-vscode.azure-account-0.9.8\dist\extension.js:265:10149)
	at processImmediate (internal/timers.js:461:21)
[2021-05-12 17:17:49.926] [exthost] [debug] ProxyResolver#resolveProxy cached https://login.microsoftonline.com/common/oauth2/token?api-version=1.0 DIRECT 
Error: Error for stack trace
	at resolveProxy (c:\Users\<username>\AppData\Local\Programs\Microsoft VS Code\resources\app\node_modules.asar\vscode-proxy-agent\out\index.js:105:69)
	at c:\Users\<username>\AppData\Local\Programs\Microsoft VS Code\resources\app\node_modules.asar\vscode-proxy-agent\out\index.js:293:77
	at new Promise (<anonymous>)
	at _PacProxyAgent.resolveP [as resolver] (c:\Users\<username>\AppData\Local\Programs\Microsoft VS Code\resources\app\node_modules.asar\vscode-proxy-agent\out\index.js:293:54)
	at _PacProxyAgent.<anonymous> (c:\Users\<username>\AppData\Local\Programs\Microsoft VS Code\resources\app\node_modules.asar\vscode-proxy-agent\out\agent.js:71:37)
	at Generator.next (<anonymous>)
	at c:\Users\<username>\AppData\Local\Programs\Microsoft VS Code\resources\app\node_modules.asar\vscode-proxy-agent\out\agent.js:8:71
	at new Promise (<anonymous>)
	at __awaiter (c:\Users\<username>\AppData\Local\Programs\Microsoft VS Code\resources\app\node_modules.asar\vscode-proxy-agent\out\agent.js:4:12)
	at _PacProxyAgent.callback (c:\Users\<username>\AppData\Local\Programs\Microsoft VS Code\resources\app\node_modules.asar\vscode-proxy-agent\out\agent.js:53:16)
	at _PacProxyAgent.addRequest (c:\Users\<username>\AppData\Local\Programs\Microsoft VS Code\resources\app\node_modules.asar\vscode-proxy-agent\node_modules\agent-base\dist\src\index.js:184:38)
	at new ClientRequest (_http_client.js:306:16)
	at request (https.js:313:10)
	at Object.patched (c:\Users\<username>\AppData\Local\Programs\Microsoft VS Code\resources\app\node_modules.asar\vscode-proxy-agent\out\index.js:297:24)
	at Object.i.request (c:\Users\<username>\.vscode\extensions\ms-vscode.azure-account-0.9.8\dist\extension.js:211:101276)
	at Object.i.request.<computed>.i.request (c:\Users\<username>\.vscode\extensions\ms-vscode.azure-account-0.9.8\dist\extension.js:234:48887)
	at B.start (c:\Users\<username>\.vscode\extensions\ms-vscode.azure-account-0.9.8\dist\extension.js:265:11770)
	at B.write (c:\Users\<username>\.vscode\extensions\ms-vscode.azure-account-0.9.8\dist\extension.js:265:22017)
	at e (c:\Users\<username>\.vscode\extensions\ms-vscode.azure-account-0.9.8\dist\extension.js:265:9649)
	at Immediate._onImmediate (c:\Users\<username>\.vscode\extensions\ms-vscode.azure-account-0.9.8\dist\extension.js:265:10149)
	at processImmediate (internal/timers.js:461:21)
[2021-05-12 17:17:50.450] [exthost] [debug] ProxyResolver#resolveProxy cached https://login.microsoftonline.com/common/oauth2/token?api-version=1.0 DIRECT 
Error: Error for stack trace
	at resolveProxy (c:\Users\<username>\AppData\Local\Programs\Microsoft VS Code\resources\app\node_modules.asar\vscode-proxy-agent\out\index.js:105:69)
	at c:\Users\<username>\AppData\Local\Programs\Microsoft VS Code\resources\app\node_modules.asar\vscode-proxy-agent\out\index.js:293:77
	at new Promise (<anonymous>)
	at _PacProxyAgent.resolveP [as resolver] (c:\Users\<username>\AppData\Local\Programs\Microsoft VS Code\resources\app\node_modules.asar\vscode-proxy-agent\out\index.js:293:54)
	at _PacProxyAgent.<anonymous> (c:\Users\<username>\AppData\Local\Programs\Microsoft VS Code\resources\app\node_modules.asar\vscode-proxy-agent\out\agent.js:71:37)
	at Generator.next (<anonymous>)
	at c:\Users\<username>\AppData\Local\Programs\Microsoft VS Code\resources\app\node_modules.asar\vscode-proxy-agent\out\agent.js:8:71
	at new Promise (<anonymous>)
	at __awaiter (c:\Users\<username>\AppData\Local\Programs\Microsoft VS Code\resources\app\node_modules.asar\vscode-proxy-agent\out\agent.js:4:12)
	at _PacProxyAgent.callback (c:\Users\<username>\AppData\Local\Programs\Microsoft VS Code\resources\app\node_modules.asar\vscode-proxy-agent\out\agent.js:53:16)
	at _PacProxyAgent.addRequest (c:\Users\<username>\AppData\Local\Programs\Microsoft VS Code\resources\app\node_modules.asar\vscode-proxy-agent\node_modules\agent-base\dist\src\index.js:184:38)
	at new ClientRequest (_http_client.js:306:16)
	at request (https.js:313:10)
	at Object.patched (c:\Users\<username>\AppData\Local\Programs\Microsoft VS Code\resources\app\node_modules.asar\vscode-proxy-agent\out\index.js:297:24)
	at Object.i.request (c:\Users\<username>\.vscode\extensions\ms-vscode.azure-account-0.9.8\dist\extension.js:211:101276)
	at Object.i.request.<computed>.i.request (c:\Users\<username>\.vscode\extensions\ms-vscode.azure-account-0.9.8\dist\extension.js:234:48887)
	at B.start (c:\Users\<username>\.vscode\extensions\ms-vscode.azure-account-0.9.8\dist\extension.js:265:11770)
	at B.write (c:\Users\<username>\.vscode\extensions\ms-vscode.azure-account-0.9.8\dist\extension.js:265:22017)
	at e (c:\Users\<username>\.vscode\extensions\ms-vscode.azure-account-0.9.8\dist\extension.js:265:9649)
	at Immediate._onImmediate (c:\Users\<username>\.vscode\extensions\ms-vscode.azure-account-0.9.8\dist\extension.js:265:10149)
	at processImmediate (internal/timers.js:461:21)
[2021-05-12 17:17:50.915] [exthost] [debug] ProxyResolver#resolveProxy https://management.azure.com/tenants?api-version=2016-06-01 PROXY [redacted_proxy] 
Error: Error for stack trace
	at resolveProxy (c:\Users\<username>\AppData\Local\Programs\Microsoft VS Code\resources\app\node_modules.asar\vscode-proxy-agent\out\index.js:105:69)
	at c:\Users\<username>\AppData\Local\Programs\Microsoft VS Code\resources\app\node_modules.asar\vscode-proxy-agent\out\index.js:293:77
	at new Promise (<anonymous>)
	at _PacProxyAgent.resolveP [as resolver] (c:\Users\<username>\AppData\Local\Programs\Microsoft VS Code\resources\app\node_modules.asar\vscode-proxy-agent\out\index.js:293:54)
	at _PacProxyAgent.<anonymous> (c:\Users\<username>\AppData\Local\Programs\Microsoft VS Code\resources\app\node_modules.asar\vscode-proxy-agent\out\agent.js:71:37)
	at Generator.next (<anonymous>)
	at c:\Users\<username>\AppData\Local\Programs\Microsoft VS Code\resources\app\node_modules.asar\vscode-proxy-agent\out\agent.js:8:71
	at new Promise (<anonymous>)
	at __awaiter (c:\Users\<username>\AppData\Local\Programs\Microsoft VS Code\resources\app\node_modules.asar\vscode-proxy-agent\out\agent.js:4:12)
	at _PacProxyAgent.callback (c:\Users\<username>\AppData\Local\Programs\Microsoft VS Code\resources\app\node_modules.asar\vscode-proxy-agent\out\agent.js:53:16)
	at _PacProxyAgent.addRequest (c:\Users\<username>\AppData\Local\Programs\Microsoft VS Code\resources\app\node_modules.asar\vscode-proxy-agent\node_modules\agent-base\dist\src\index.js:184:38)
	at new ClientRequest (_http_client.js:306:16)
	at request (https.js:313:10)
	at Object.patched (c:\Users\<username>\AppData\Local\Programs\Microsoft VS Code\resources\app\node_modules.asar\vscode-proxy-agent\out\index.js:297:24)
	at Object.i.request (c:\Users\<username>\.vscode\extensions\ms-vscode.azure-account-0.9.8\dist\extension.js:211:101276)
	at i.request.<computed>.i.request (c:\Users\<username>\.vscode\extensions\ms-vscode.azure-account-0.9.8\dist\extension.js:234:48887)
	at c:\Users\<username>\.vscode\extensions\ms-vscode.azure-account-0.9.8\dist\extension.js:253:19669
	at new Promise (<anonymous>)
	at G (c:\Users\<username>\.vscode\extensions\ms-vscode.azure-account-0.9.8\dist\extension.js:253:18420)
	at t.<anonymous> (c:\Users\<username>\.vscode\extensions\ms-vscode.azure-account-0.9.8\dist\extension.js:16:45300)
	at c:\Users\<username>\.vscode\extensions\ms-vscode.azure-account-0.9.8\dist\extension.js:211:1761
	at Object.next (c:\Users\<username>\.vscode\extensions\ms-vscode.azure-account-0.9.8\dist\extension.js:211:1866)
	at c:\Users\<username>\.vscode\extensions\ms-vscode.azure-account-0.9.8\dist\extension.js:211:803
	at new Promise (<anonymous>)
	at a (c:\Users\<username>\.vscode\extensions\ms-vscode.azure-account-0.9.8\dist\extension.js:211:548)
	at t.fetch (c:\Users\<username>\.vscode\extensions\ms-vscode.azure-account-0.9.8\dist\extension.js:16:45226)
	at t.<anonymous> (c:\Users\<username>\.vscode\extensions\ms-vscode.azure-account-0.9.8\dist\extension.js:16:43849)
	at c:\Users\<username>\.vscode\extensions\ms-vscode.azure-account-0.9.8\dist\extension.js:211:1761
	at Object.next (c:\Users\<username>\.vscode\extensions\ms-vscode.azure-account-0.9.8\dist\extension.js:211:1866)
	at a (c:\Users\<username>\.vscode\extensions\ms-vscode.azure-account-0.9.8\dist\extension.js:211:605)
	at processTicksAndRejections (internal/process/task_queues.js:93:5)
```
Followed by 2 minutes of call to microsoft login. 

I have tried the following:
________________________________
Manual specify the proxy server and add the root certificate to node using environment variables

The proxy was always resolved to the same proxy server but the results did not change.

_________________________________

Add the win-ca extension to get the windows root certificate store. 

I still get the same bug reports.

___________________________________

I do not have any issue with other tool that use openssl like github and otherwise, vscode is able to connect to internet to load the extension list and download.

**Comment by chrmarti** [comment]
The log shows it going directly to login.microsoftonline.com, but then using a proxy for vscode-redirect.azurewebsites.net. Can you change your configuration to let vscode-redirect.azurewebsites.net also be connected to directly without proxy?

Also check your log for entries containing `ProxyResolver#getCaCertificates` and append them here.

**Comment by wwlorey** [comment]
Closing due to lack of activity.
