### ISSUE TITLE
Azure: Sign In redirected to URI malformed error

### ISSUE THREAD

**Issue by nor-ko** [microsoft/vscode-azure-account#414]
Extension Version: Azure Account v0.9.11
VSCode Version: 1.63.2 (system setup)
commit: 899d46d82c4c95423fb7e10e68eba52050e30ba3
Date : 2021-12-15T09:40:02.816Z
Electron: 13.5.2
Chromium: 91.0.4472.164
Node.js: 14.16.0
V8: 9.1.269.39-electron.0
OS: Windows_NT x64 10.0.19043

reproduce step:

1. press F1, Azure: Sign In
2. Try to sign-in from launched browser `https://login.microsoftonline.com/common/oauth2/authorize?response_type=code&client_id=aebc6443-996d-45c2-90f0-388ff96faa56&redirect_uri=https%3A%2F%2Fvscode-redirect.azurewebsites.net%2F&state=55505,A5oNpa%2B%2FUMlin1rYvax%2FOA%3D%3D&resource=https%3A%2F%2Fmanagement.core.windows.net%2F&prompt=select_account`
3. I sign-in from the browser
4. redirected to `http://127.0.0.1:55505/?error=URI%20malformed`
5. URI malformed error message dialog popup on VSCode window.

Notice: my company MS account integrated with Okta SSO, and tried with/ without signed-in situation. 

log (extension host) says...

At the timing browser launches,

```text
2022-01-27 10:16:06.547] [exthost] [debug] ProxyResolver#resolveProxy settings https://vscode-redirect.azurewebsites.net/?state=3333,cccc PROXY <my-proxy-settings> 
Error: Error for stack trace
    at resolveProxy (c:\Program Files\Microsoft VS Code\resources\app\node_modules.asar\vscode-proxy-agent\out\index.js:105:69)
    at c:\Program Files\Microsoft VS Code\resources\app\node_modules.asar\vscode-proxy-agent\out\index.js:293:77
    at new Promise (<anonymous>)
    at _PacProxyAgent.resolveP (c:\Program Files\Microsoft VS Code\resources\app\node_modules.asar\vscode-proxy-agent\out\index.js:293:54)
    at _PacProxyAgent.<anonymous> (c:\Program Files\Microsoft VS Code\resources\app\node_modules.asar\vscode-proxy-agent\out\agent.js:71:37)
    at Generator.next (<anonymous>)
    at c:\Program Files\Microsoft VS Code\resources\app\node_modules.asar\vscode-proxy-agent\out\agent.js:8:71
    at new Promise (<anonymous>)
    at __awaiter (c:\Program Files\Microsoft VS Code\resources\app\node_modules.asar\vscode-proxy-agent\out\agent.js:4:12)
    at _PacProxyAgent.callback (c:\Program Files\Microsoft VS Code\resources\app\node_modules.asar\vscode-proxy-agent\out\agent.js:53:16)
    at _PacProxyAgent.addRequest (c:\Program Files\Microsoft VS Code\resources\app\node_modules.asar\vscode-proxy-agent\node_modules\agent-base\dist\src\index.js:184:38)
    at new ClientRequest (_http_client.js:306:16)
    at request (https.js:313:10)
    at Object.patched (c:\Program Files\Microsoft VS Code\resources\app\node_modules.asar\vscode-proxy-agent\out\index.js:297:24)
    at Object.i.request (c:\Users\10379476\.vscode\extensions\ms-vscode.azure-account-0.9.11\dist\extension.js:646:101276)
    at Object.i.request.<computed>.i.request [as request] (c:\Users\10379476\.vscode\extensions\ms-vscode.azure-account-0.9.11\dist\extension.js:669:189472)
    at Object.i.get (c:\Users\10379476\.vscode\extensions\ms-vscode.azure-account-0.9.11\dist\extension.js:669:189640)
    at c:\Users\10379476\.vscode\extensions\ms-vscode.azure-account-0.9.11\dist\extension.js:881:41559
    at new Promise (<anonymous>)
    at Object.<anonymous> (c:\Users\10379476\.vscode\extensions\ms-vscode.azure-account-0.9.11\dist\extension.js:881:41532)
    at Generator.next (<anonymous>)
    at c:\Users\10379476\.vscode\extensions\ms-vscode.azure-account-0.9.11\dist\extension.js:881:40947
    at new Promise (<anonymous>)
    at n (c:\Users\10379476\.vscode\extensions\ms-vscode.azure-account-0.9.11\dist\extension.js:881:40692)
    at Object.t.checkRedirectServer (c:\Users\10379476\.vscode\extensions\ms-vscode.azure-account-0.9.11\dist\extension.js:881:41470)
    at t.AzureLoginHelper.<anonymous> (c:\Users\10379476\.vscode\extensions\ms-vscode.azure-account-0.9.11\dist\extension.js:881:11140)
    at Generator.next (<anonymous>)
    at a (c:\Users\10379476\.vscode\extensions\ms-vscode.azure-account-0.9.11\dist\extension.js:881:922)
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
[2022-01-27 10:36:49.417] [exthost] [trace] CommandsConverter#CREATE azure-account.login 87
[2022-01-27 10:36:49.417] [exthost] [trace] CommandsConverter#CREATE azure-account.login 88
[2022-01-27 10:36:49.417] [exthost] [trace] CommandsConverter#CREATE azure-account.login 89
[2022-01-27 10:36:49.417] [exthost] [trace] CommandsConverter#CREATE azure-account.login 90
[2022-01-27 10:36:49.425] [exthost] [trace] CommandsConverter#CREATE azure-account.login 91
```

the timing signed in, no error raised.

```text
[2022-01-27 10:37:01.121] [exthost] [trace] CommandsConverter#DISPOSE 87
[2022-01-27 10:37:01.121] [exthost] [trace] CommandsConverter#DISPOSE 91
[2022-01-27 10:37:01.121] [exthost] [trace] CommandsConverter#DISPOSE 89
[2022-01-27 10:37:01.121] [exthost] [trace] CommandsConverter#DISPOSE 92
[2022-01-27 10:37:01.121] [exthost] [trace] CommandsConverter#DISPOSE 88
[2022-01-27 10:37:01.121] [exthost] [trace] CommandsConverter#DISPOSE 90
[2022-01-27 10:37:01.152] [exthost] [trace] CommandsConverter#CREATE azure-account.login 93
[2022-01-27 10:37:01.152] [exthost] [trace] CommandsConverter#CREATE azure-account.createAccount 94
[2022-01-27 10:37:01.152] [exthost] [trace] CommandsConverter#CREATE azure-account.login 95
[2022-01-27 10:37:01.152] [exthost] [trace] CommandsConverter#CREATE azure-account.createAccount 96
[2022-01-27 10:37:01.152] [exthost] [trace] CommandsConverter#CREATE azure-account.login 97
[2022-01-27 10:37:01.152] [exthost] [trace] CommandsConverter#CREATE azure-account.createAccount 98
[2022-01-27 10:37:01.152] [exthost] [trace] CommandsConverter#CREATE azure-account.login 99
[2022-01-27 10:37:01.152] [exthost] [trace] CommandsConverter#CREATE azure-account.createAccount 100
[2022-01-27 10:37:01.159] [exthost] [trace] CommandsConverter#CREATE azure-account.login 101
[2022-01-27 10:37:01.159] [exthost] [trace] CommandsConverter#CREATE azure-account.createAccount 102
```
output(Azure account) put following single line.

```text
Error: URI malformed
```

browser's network trace

```text
{
GET https://login.microsoftonline.com/common/reprocess?ctx=xxx&sessionid=yyy"
status: 302
Location: https://vscode-redirect.azurewebsites.net/?code=xxx&state=yyy&session_state=zzz

GET https://vscode-redirect.azurewebsites.net/?code=xxx&state=yyy&session_state=zzz
status: 302
Location: http://127.0.0.1:51765/callback?code=xxx&state=yyy&session_state=zzz

GET http://127.0.0.1:51765/callback?code=xxx&state=yyy&session_state=zzz
status: 302
Location: /?error=URI%20malformed
```

**Comment by nor-ko** [comment]
Sorry, resolved.

I had SSLKEYLOGFILE system environment for wireshark tracing.
For VSCode user, no permission to the file. It looks cause this.
I installed az-cli to try az login, and notice the cli refer the file.
After set user environment to override SSLKEYLOGFILE, both cli and extensions work well.
