### ISSUE TITLE
Signin failed: Verification code expired

### ISSUE THREAD

**Issue by TonyHernandezAtMS** [Microsoft/vscode-azure-account#44]
After I complete device login through browser, I see the following error in developer console:
`Error: Acquiring token with device code failed
	at C:\Users\somebody\.vscode\extensions\ms-vscode.azure-account-0.3.3\out\src\azure-account.js:587:28
	at C:\Users\somebody\.vscode\extensions\ms-vscode.azure-account-0.3.3\node_modules\adal-node\lib\token-request.js:593:8
	at C:\Users\somebody\.vscode\extensions\ms-vscode.azure-account-0.3.3\node_modules\adal-node\lib\oauth2client.js:503:10
	at C:\Users\somebody\.vscode\extensions\ms-vscode.azure-account-0.3.3\node_modules\async\dist\async.js:4590:26
	at C:\Users\somebody\.vscode\extensions\ms-vscode.azure-account-0.3.3\node_modules\adal-node\lib\oauth2client.js:415:13
	at Request._callback (C:\Users\somebody\.vscode\extensions\ms-vscode.azure-account-0.3.3\node_modules\adal-node\lib\util.js:133:7)
	at Request.self.callback (C:\Users\somebody\.vscode\extensions\ms-vscode.azure-account-0.3.3\node_modules\request\request.js:188:22)
	at emitTwo (events.js:106:13)
	at Request.emit (events.js:194:7)
	at Request.<anonymous> (C:\Users\somebody\.vscode\extensions\ms-vscode.azure-account-0.3.3\node_modules\request\request.js:1171:10)
	at emitOne (events.js:96:13)
	at Request.emit (events.js:191:7)
	at IncomingMessage.<anonymous> (C:\Users\somebody\.vscode\extensions\ms-vscode.azure-account-0.3.3\node_modules\request\request.js:1091:12)
	at Object.onceWrapper (events.js:293:19)
	at emitNone (events.js:91:20)
	at IncomingMessage.emit (events.js:188:7)
	at endReadableNT (_stream_readable.js:975:12)
	at _combinedTickCallback (internal/process/next_tick.js:80:11)
	at process._tickCallback (internal/process/next_tick.js:104:9)
t.log @ console.ts:136
console.ts:136 [Extension Host]% Object
t.log @ console.ts:136 `

`Error: Acquiring token with device code failed
	at C:\Users\somebody\.vscode\extensions\ms-vscode.azure-account-0.3.3\out\src\azure-account.js:587:28
	at C:\Users\somebody\.vscode\extensions\ms-vscode.azure-account-0.3.3\node_modules\adal-node\lib\token-request.js:593:8
	at C:\Users\somebody\.vscode\extensions\ms-vscode.azure-account-0.3.3\node_modules\adal-node\lib\oauth2client.js:503:10
	at C:\Users\somebody\.vscode\extensions\ms-vscode.azure-account-0.3.3\node_modules\async\dist\async.js:4590:26
	at C:\Users\somebody\.vscode\extensions\ms-vscode.azure-account-0.3.3\node_modules\adal-node\lib\oauth2client.js:415:13
	at Request._callback (C:\Users\somebody\.vscode\extensions\ms-vscode.azure-account-0.3.3\node_modules\adal-node\lib\util.js:133:7)
	at Request.self.callback (C:\Users\somebody\.vscode\extensions\ms-vscode.azure-account-0.3.3\node_modules\request\request.js:188:22)
	at emitTwo (events.js:106:13)
	at Request.emit (events.js:194:7)
	at Request.<anonymous> (C:\Users\somebody\.vscode\extensions\ms-vscode.azure-account-0.3.3\node_modules\request\request.js:1171:10)
	at emitOne (events.js:96:13)
	at Request.emit (events.js:191:7)
	at IncomingMessage.<anonymous> (C:\Users\somebody\.vscode\extensions\ms-vscode.azure-account-0.3.3\node_modules\request\request.js:1091:12)
	at Object.onceWrapper (events.js:293:19)
	at emitNone (events.js:91:20)
	at IncomingMessage.emit (events.js:188:7)
	at endReadableNT (_stream_readable.js:975:12)
	at _combinedTickCallback (internal/process/next_tick.js:80:11)
	at process._tickCallback (internal/process/next_tick.js:104:9)
t.log @ console.ts:136
console.ts:136 [Extension Host]% Object
t.log @ console.ts:136 `

**Comment by TonyHernandezAtMS** [comment]
Here is more from the console:

[console.log](https://github.com/Microsoft/vscode-azure-account/files/1834772/console.log)

**Comment by chrmarti** [comment]
It says the verification code expired, meaning that the code you pasted in the website was no longer valid. Does it show the same error message when you retry? Does the website tell you the sign-in was successful?

**Comment by TonyHernandezAtMS** [comment]
I am able to successfully login with the browser. The browser states that login is successful. Returning to vscode, after waiting a moment (I assume there is a polling mechanism), the UI will transition from the "waiting swirly" back to "Login to Azure". Opening the developer console, I see the errors previously mentioned.

I've tried logging in with other browsers and they all say that login was successful.

**Comment by chrmarti** [comment]
The Azure Account extension's command is named "Azure: Sign In". Could you check if that is the one you run? Maybe you are running a command from a different extension. (Azure Account has no "waiting swirly".)
