### ISSUE TITLE
Exception when calling credentials2.getToken after upgrading to v0.10.0

### ISSUE THREAD

**Issue by sevillal** [microsoft/vscode-azure-account#457]
- VS Code Version: 1.64.2
- Azure Account Extension Version: v0.10.0
- OS Version: Windows 11

Steps to Reproduce:

1. Open a folder in vscode
2. Start using extension version 0.9.11
2. Sign in
3. Upgrade to version 0.10.0
4. Using Azure ML Extension run command "Azure ML: Set Default Workspace" and select a default workspace
5. Reload the window
6. As part of the Azure ML Extension startup operations it will request credentials2.getToken on the subscription of the default workspace
7. We are seeing the following exception:
`[Error - 2022-02-17 21:44:53.314] TypeError: Cannot read property 'trim' of undefined
    at <REDACTED>.vscode\extensions\ms-vscode.azure-account-0.10.0\dist\extension.bundle.js:2:168982
    at Array.map (<anonymous>)
    at Function.trimArrayEntries (<REDACTED>\.vscode\extensions\ms-vscode.azure-account-0.10.0\dist\extension.bundle.js:2:168956)
    at new ScopeSet (<REDACTED>\.vscode\extensions\ms-vscode.azure-account-0.10.0\dist\extension.bundle.js:2:185274)
    at SilentFlowClient.<anonymous> (<REDACTED>\.vscode\extensions\ms-vscode.azure-account-0.10.0\dist\extension.bundle.js:2:247421)
    at step (<REDACTED>\.vscode\extensions\ms-vscode.azure-account-0.10.0\dist\extension.bundle.js:2:147853)
    at Object.next (<REDACTED>\.vscode\extensions\ms-vscode.azure-account-0.10.0\dist\extension.bundle.js:2:147958)
    at <REDACTED>\.vscode\extensions\ms-vscode.azure-account-0.10.0\dist\extension.bundle.js:2:146868
    at new Promise (<anonymous>)
    at __awaiter (<REDACTED>\.vscode\extensions\ms-vscode.azure-account-0.10.0\dist\extension.bundle.js:2:146554)
    at SilentFlowClient.acquireCachedToken (<REDACTED>\.vscode\extensions\ms-vscode.azure-account-0.10.0\dist\extension.bundle.js:2:246780)
    at SilentFlowClient.<anonymous> (<REDACTED>\.vscode\extensions\ms-vscode.azure-account-0.10.0\dist\extension.bundle.js:2:246481)
    at step (<REDACTED>\.vscode\extensions\ms-vscode.azure-account-0.10.0\dist\extension.bundle.js:2:147853)
    at Object.next (<REDACTED>\.vscode\extensions\ms-vscode.azure-account-0.10.0\dist\extension.bundle.js:2:147958)
    at <REDACTED>\.vscode\extensions\ms-vscode.azure-account-0.10.0\dist\extension.bundle.js:2:146868
    at new Promise (<anonymous>)
    at __awaiter (<REDACTED>\.vscode\extensions\ms-vscode.azure-account-0.10.0\dist\extension.bundle.js:2:146554)
    at SilentFlowClient.acquireToken (<REDACTED>\.vscode\extensions\ms-vscode.azure-account-0.10.0\dist\extension.bundle.js:2:246337)
    at PublicClientApplication.acquireTokenSilent (<REDACTED>\.vscode\extensions\ms-vscode.azure-account-0.10.0\dist\extension.bundle.js:2:296828)
    at processTicksAndRejections (internal/process/task_queues.js:93:5) []`

**Comment by wwlorey** [comment]
> I think maybe we should consider having a default argument given here?

I agree. This makes sense because the original filer of https://github.com/microsoft/vscode-tools-for-ai/issues/1464 is on Insiders so more likely that they're using MSAL and hitting that version of `getToken` that requires a scope argument.

**Comment by sevillal** [comment]
@wwlorey is MSAL the default library once customers upgrade from  0.9.11 to 0.10.0?

**Comment by bwateratmsft** [comment]
@sevillal we are doing experimentation to control it. If you are on VSCode Insiders, there is currently a 50/50 chance you will have MSAL. If you are not on Insiders, currently the only way to get to MSAL is to set it manually in settings.

**Comment by sevillal** [comment]
@bwateratmsft I will double check but I guess I moved from 0.9.11 to 0.10.0 in VS Code stable and I got the MSAL config by default, would that be possible?

**Comment by bwateratmsft** [comment]
Ah, yes that is possible. I just double checked our targeting and realized it includes internal (MSFT) at 50/50 as well. So you could have it by default.
