### ISSUE TITLE
Unable to sign in to Azure App Service via VS Code - getting No response from server error

### ISSUE THREAD

**Issue by bengrah-miller** [microsoft/vscode-azure-account#495]
Does this occur consistently? Yes
Repro steps:

1. Install Azure App Service plugin into VS Code
2. Click Sign in
3. Website to sign in should open
4. Sign in with correct credentials
5. You get a page that states you're signed in successful, and that you can close the page

_Expected Result_

See the list of app services 

_Actual Result_

Still not signed in, get the following error

Action: azure-account.login
Error type: Error
Error Message: No response from the server

Version: 0.10.0
OS: win32
OS Release: 10.0.17763
Product: Visual Studio Code
Product Version: 1.63.2
Language: en

<details>
<summary>Call Stack</summary>

```
Logger.createError extension.bundle.js:2:788524
extension.bundle.js:2:801557extension.bundle.js:2:801557
processTicksAndRejections task_queues.js:93:5
```

</details>

**Comment by wwlorey** [comment]
Thanks for filing @bengrah-miller. As a workaround for now, please downgrade to version 0.9.11 of the extension using the method demonstrated [here](https://code.visualstudio.com/updates/v1_30#_install-previous-versions).

**Comment by bengrah-miller** [comment]
Hi @wwlorey - thanks for getting back to me. I downgraded to 0.9.1 (there wasn't an option for 0.9.11)  and tried again, but getting the same issue. I am getting the following on the _Output_ screen on VS Code for _Azure Account_

```
Thu, 03 Mar 2022 11:24:14 GMT:7eb2e0e4-710d-4d15-9b78-c8d192164ccb - OAuth2Client: ERROR: No response from the server
Stack:
Error: No response from the server
	at Logger.createError (c:\Users\bengrah\.vscode\extensions\ms-vscode.azure-account-0.10.0\dist\extension.bundle.js:2:788524)
	at c:\Users\bengrah\.vscode\extensions\ms-vscode.azure-account-0.10.0\dist\extension.bundle.js:2:801557
	at processTicksAndRejections (internal/process/task_queues.js:93:5)
Error: No response from the server
Error: No response from the server
```

**Comment by yahanda** [comment]
+1, my customer is facing the same issue.

**Comment by yahanda** [comment]
Feedback from the customer, issue is now resolved with version 0.9.11. Thanks!

**Comment by bengrah-miller** [comment]
@yahanda I'm not able to see a 0.9.11 version - can you assist?

bengra
<img width="715" alt="20220304-0746-VScode" src="https://user-images.githubusercontent.com/11442626/156721432-8f63e36d-4159-4adf-8fdd-43d1402131c3.png">
h

**Comment by yahanda** [comment]
Hi @bengrah-miller, you should change the version of Azure Account, not of Azure App Service.

**Comment by bengrah-miller** [comment]
@yahanda Thanks for that - I've downgraded _Azure Account_ and that resolved my issue. Thanks again.

**Comment by wwlorey** [comment]
@bengrah-miller, @yahanda please upgrade to [version 0.10.1](https://github.com/microsoft/vscode-azure-account/releases/tag/v0.10.1) and let us know if you're still running into this problem.

![Screen Shot 2022-03-23 at 10 08 54 AM](https://user-images.githubusercontent.com/22795803/159756540-6f5caff2-beee-4bd9-8617-63959f03e95b.png)

**Comment by bengrah-miller** [comment]
Hi @wwlorey - still getting the same issue with the updated version. This is what I'm getting on the Output for _Azure Account_

```
\r\n \r\n \r\n \r\n \r\n \r\n Internet Access Login\r\n \r\n \r\n \r\n \n \n Your organization is using an internet security provider to protect your web browsing. We detected that you are connecting from outside your organization and need to determine who you are before proceeding.\n \n\n \n \n \n \n \n \n \n \n \n \n \n \n Log in if you already have credentials to access the internet through your company workstation, otherwise please register first.

\n Login\n \n 
\n Forgot password [\"https://www.mailcontrol.com/enduser/forgot/index.mhtml?ntlmid=&url=https%3A//login.microsoftonline.com/common/oauth2/token%3Fapi-version%3D1.0&meth=POST\"]\n \n 
\n\n \n \n \n \n \n Not Registered? [\"javascript:document.getElementById('register_form').submit()\"]\n \n\n \n \n \n \n \n \n \n If you have reached this page in error or have the endpoint client installed on your workstation,\nplease see further instructions on the support site [\"http://www.websense.com/support/article/kbarticle/Why-cloud-internet-access-login\"].\n \r\n \r\n \r\n \r\n \r\n \r\n \r\n \r\n \r\n \r\n \r\n \r\n \r\n \r\n \r\n \r\n \r\n
```

Ben.

**Comment by wwlorey** [comment]
@bengrah-miller what happens when you sign in with the `Azure: Sign In with Device Code` command?

**Comment by bengrah-miller** [comment]
Hi @wwlorey - OK thanks. I've tried that this morning but still not working. I get the following on _Output/Azure Account_ log

```
Error: Get Device Code request returned http error: 403 and server response: "<!DOCTYPE html public \"-//W3C//DTD HTML 4.0 Transitional//en\" \"http://www.w3.org/TR/html4/loose.dtd\">\r\n   <html xmlns=\"http://www.w3.org/1999/xhtml\" xml:lang=\"en\" lang=\"en\">\r\n    <head>\r\n        <meta charset=\"utf-8\"/>\r\n        <base href=\"http://www.mailcontrol.com\">\r\n        <meta name=\"viewport\" content=\"width=device-width, initial-scale=1.0, maximum-scale=1.0, user-scalable=0\"/>\r\n        \r\n        <link rel=\"stylesheet\" href=\"http://www.mailcontrol.com/http-resources/bootstrap/css/bootstrap.css\" type=\"text/css\">\r\n        <link rel=\"stylesheet\" href=\"http://www.mailcontrol.com/http-resources/bootstrap/css/bootstrap-responsive.css\" type=\"text/css\">\r\n        <link rel=\"stylesheet\" href=\"http://www.mailcontrol.com/http-resources/notification-pages/notification.css\" type=\"text/css\">\r\n        <!--[if IE ]>\r\n           <link rel=\"stylesheet\" href=\"http://www.mailcontrol.com/http-resources/notification-pages/notification-ie.css\" type=\"text/css\">\r\n           <script src=\"http://www.mailcontrol.com/http-resources/head.js\"></script>\r\n        <![endif]-->\r\n        <!--[if IE 6]>\r\n            <link rel=\"stylesheet\" href=\"http://www.mailcontrol.com/http-resources/bootstrap/css/bootstrap-ie6.min.css\" type=\"text/css\">\r\n            <link rel=\"stylesheet\" href=\"http://www.mailcontrol.com/http-resources/bootstrap/css/ie.css\" type=\"text/css\">\r\n            <link rel=\"stylesheet\" href=\"http://www.mailcontrol.com/http-resources/notification-pages/notification-ie6.css\" type=\"text/css\">\r\n\r\n            <script src=\"http://www.mailcontrol.com/http-resources/notification-pages/jquery-1.4.2.min.js\"></script>\r\n            <script src=\"http://www.mailcontrol.com/http-resources/ie6_joined_classes.js\"></script>\r\n            <script>\r\n              var IEPNGFix = window.IEPNGFix || {};\r\n              IEPNGFix.blankImg = \"http://www.mailcontrol.com/http-resources/iepngfix/blank.gif\";\r\n            </script>\r\n            <script src=\"http://www.mailcontrol.com/http-resources/iepngfix/jquery.iepngfix.js\"></script>\r\n        <![endif]-->\r\n        <style id=\"\"></style>\r\n        <title id=\"\">Internet Access Login</title>\r\n    </head>\r\n    <body class=\"loading\" id=\"\">\r\n        <div class=\"container\" id=\"container\">\r\n            <div class=\"row\">\r\n                <div class=\"span10 offset1\" id=\"notify\">\r\n                    <div class=\"notify-title-box\">\r\n                        <img id=\"title_icon\" src=\"http://www.mailcontrol.com/http-resources/notification-pages/icons60/login.png\" height=\"60\" width=\"60\" class=\"\" />\r\n                        <span id=\"notify-title\" class=\"\" >Internet Access Login</span>\r\n                        <div id=\"titleBlink\"></div>\r\n                    </div>\r\n                    <div class=\"notify-box\">\r\n                        <div id=\"notify-content\" class=\"\">\n      <div class=\"row\">\n            <div class=\"span9 explanation\">Your organization is using an internet security provider to protect your web browsing. We detected that you are connecting from outside your organization and need to determine who you are before proceeding.</div>\n    </div>\n\n      <div class=\"row\">\n          <div class=\"offset1 span7\" id=\"login-panel\">\n             <table class=\"login-register one-column\" cellpadding=\"15px\">\n               <tbody>\n                  <tr valign=\"top\" align=\"left\">\n                     <td align=\"center\">\n                          <form method=\"POST\" ACTION=\"http://proxy-login.blackspider.com/\">\n                            <span class=\"hidden\">  <input type='hidden' name='meth' value='POST'/>\n  <input type='hidden' name='url' value='https%3A//login.microsoftonline.com/common/oauth2/devicecode%3Fapi-version%3D1.0'/>\n  <input type='hidden' name='ip' value='5.67.163.8'/>\n  <input type='hidden' name='service' value='webdefence'/>\n  <input type='hidden' name='sessionid' value=''/></span>\n                            <p style=\"text-align:left\">Log in if you already have credentials to access the internet through your company workstation, otherwise please register first.</p>\n                            <button id=\"proxy_login_button\" type=\"submit\" class=\"big-login\" contentEditable=\"false\">Login</button>\n                          </form>\n                             <br/>\n                        <a href=\"https://www.mailcontrol.com/enduser/forgot/index.mhtml?ntlmid=&url=https%3A//login.microsoftonline.com/common/oauth2/devicecode%3Fapi-version%3D1.0&meth=POST\">Forgot password</a>\n                        \n                        <br/>\n\n                       <form method=\"POST\" ACTION=\"https://www.mailcontrol.com/enduser/reg/index.mhtml\" id=\"register_form\">\n                          <span class=\"hidden\">  <input type='hidden' name='site' value=''/>\n  <input type='hidden' name='ntlmid' value=''/>\n  <input type='hidden' name='meth' value='POST'/>\n  <input type='hidden' name='url' value='https://login.microsoftonline.com/common/oauth2/devicecode?api-version=1.0'/></span>\n                          <a href=\"javascript:document.getElementById('register_form').submit()\">Not Registered?</a>\n                       </form>\n\n                     </td>\n                 </tr>\n               </tbody>\n             </table>\n          </div>\n      </div>\n      <div class=\"row\">\n         <div class=\"span9 explanation\">If you have reached this page in error or have the endpoint client installed on your workstation,\nplease see further instructions on the <a target=\"_blank\" href=\"http://www.websense.com/support/article/kbarticle/Why-cloud-internet-access-login\">support site</a>.</div>\n </div></div>\r\n                    </div>\r\n                    <div class=\"\" id=\"footerRow\" >\r\n                        <div id=\"footer\" class=\"\">\r\n                           <img src=\"http://www.mailcontrol.com/http-resources/notification-pages/2020/notification_page_logo_145x35.png\" height=\"35\" width=\"145\" id=\"bottom-logo\" class=\"\"/>\r\n                           <span id=\"footer-text\" class=\"\" ></span>\r\n                           <div class=\"clear-float\"></div>\r\n                        </div>\r\n                        <div class=\"clear-float\"></div>\r\n                    </div>\r\n                </div>\r\n            </div>\r\n        </div>\r\n        <div class=\"clear-float\"></div>\r\n        <script src=\"http://www.mailcontrol.com/http-resources/notification-pages/empty.js\"></script>\r\n         <!--[if !(IE 6)]>\r\n            <script src=\"http://www.mailcontrol.com/http-resources/notification-pages/respond.src.js\"></script>\r\n         <![endif]-->\r\n        <!-- __DEBUG_INFO__ -->\r\n    </body>\r\n</html>"
Acquiring user code failed
```

And this pop up:

![image](https://user-images.githubusercontent.com/11442626/161210646-a815e794-503d-4251-9660-1d1599b292be.png)

Thanks,
bengrah

**Comment by bengrah-miller** [comment]
Hi @wwlorey - I've just checked and from what I can see the settings are what I'd expect them to be. To be honest, there's nothing in there I've ever made changes to, and I couldn't see any settings specifically relating to our tenant.

**Comment by alexweininger** [comment]
If you are still facing issues signing in behind a proxy, see the [Unable to Sign In While Using a Proxy section of our wiki](https://github.com/microsoft/vscode-azure-account/wiki/Troubleshooting#unable-to-sign-in-while-using-a-proxy) for possible fixes.
