### ISSUE TITLE
"certificate has expired" error when attempting to log in to Azure Stack

### ISSUE THREAD

**Issue by jamesorlando** [microsoft/vscode-azure-account#534]
- VS Code Version: 1.65.2
- Azure Account Extension Version: v0.10.1
- OS Version: Win 10 20H2 19042.1586

Steps to Reproduce:

1. Configure settings.json for Custom Cloud (Azure Stack)
2. Attempt to connect 
3. Get error about "certificate has expired" error

Only on some machines. Not sure what certificate its talking about. It is not on the stack side since other machines can connect. This is also before even being prompted for credentials.

**Comment by jamesorlando** [comment]
![image](https://user-images.githubusercontent.com/68352831/160025081-0123a811-3b72-4606-93cb-c11c5e8f0fb9.png)

**Comment by wwlorey** [comment]
Hi @jamesorlando, is there anything else in the output channel, or is it just spamming that "certificate has expired" message?

We added URL logging in a pre-release version of the extension to make debugging proxy issues easier. If you get a chance, please follow these instructions to download a private build and check the output channel for all the URLs the extension is trying to access. It's possible knowing them will help configure the proxy.

1. Download version `v0.10.2-alpha` of the extension [here](https://dev.azure.com/ms-azuretools/_apis/resources/Containers/5728292/vsix?itemPath=vsix%2Fazure-account-0.10.2-alpha.vsix).
2. Open VS Code and run the `Extensions: Install Specific Version of Extension...` command (accessible from the [command palette](https://code.visualstudio.com/docs/getstarted/userinterface#_command-palette)).
![Screen Shot 2022-02-28 at 10 19 15 AM](https://user-images.githubusercontent.com/22795803/156036649-2f02c066-7e89-470c-8300-1903fe16f563.png)
3. In the file picker: browse to the `.vsix` file you downloaded and select it.
4. After selecting the file, a notification should appear prompting you to reaload the VS Code window. Click "Reload Now".
![Screen Shot 2022-02-28 at 10 21 37 AM](https://user-images.githubusercontent.com/22795803/156037095-0e4830ed-f226-48d6-9bbd-1e2cbde08029.png)
5. Open the marketplace in VS Code. Verify that the Azure Account Extension version reads `v0.10.2-alpha`. 
7. Try signing in again and check Azure Account the output channel for more information.

**Comment by wwlorey** [comment]
Note: URL logging was added in https://github.com/microsoft/vscode-azure-account/pull/520

**Comment by jamesorlando** [comment]
This sounds super helpful. However I am getting unauthorized when I click the download link. 
 
UnauthorizedRequestException

**Comment by wwlorey** [comment]
Apologies for that - please try this link instead: https://dev.azure.com/ms-azuretools/534e1e1c-b364-44d0-b5ee-dce879a5106e/_apis/build/builds/44629/artifacts?artifactName=vsix&api-version=7.0&%24format=zip

**Comment by jamesorlando** [comment]
To answer your previous question about just spamming the message over and over, yeah it does that about every 5 seconds. 
![image](https://user-images.githubusercontent.com/68352831/160498693-d900d00e-0bfa-4b70-b2d3-2bf007db49d1.png)

**Comment by jamesorlando** [comment]
Seems to be getting to ligin.microsoftonline.com (but never opens a web browser to sign in): 
![image](https://user-images.githubusercontent.com/68352831/160499133-da9ddc8d-8c06-4eec-8541-0397ea82374f.png)

**Comment by wwlorey** [comment]
@jamesorlando what happens when you sign in with the `Azure: Sign In with Device Code` command?

**Comment by jamesorlando** [comment]
@wwlorey I get the same thing.

**Comment by jamesorlando** [comment]
Are there any other logs I could be looking at?

**Comment by jamesorlando** [comment]
Found a log. I redacted the user name and the proxy fqdn. But the proxy address was correct. Any insight into the errors here? 

[2022-04-04 11:05:36.045] [exthost] [debug] ProxyResolver#resolveProxy cached https://login.microsoftonline.com/ PROXY proxy.<FQDN>:80
Error: Error for stack trace
at resolveProxy (c:\Users\<user>\AppData\Local\Programs\Microsoft VS Code\resources\app\node_modules.asar\vscode-proxy-agent\out\index.js:105:69)
at c:\Users\<user>\AppData\Local\Programs\Microsoft VS Code\resources\app\node_modules.asar\vscode-proxy-agent\out\index.js:294:77
at new Promise (<anonymous>)
at _PacProxyAgent.resolveP [as resolver] (c:\Users\<user>\AppData\Local\Programs\Microsoft VS Code\resources\app\node_modules.asar\vscode-proxy-agent\out\index.js:294:54)
at _PacProxyAgent.<anonymous> (c:\Users\<user>\AppData\Local\Programs\Microsoft VS Code\resources\app\node_modules.asar\vscode-proxy-agent\out\agent.js:70:37)
at Generator.next (<anonymous>)
at c:\Users\<user>\AppData\Local\Programs\Microsoft VS Code\resources\app\node_modules.asar\vscode-proxy-agent\out\agent.js:8:71
at new Promise (<anonymous>)
at __awaiter (c:\Users\<user>\AppData\Local\Programs\Microsoft VS Code\resources\app\node_modules.asar\vscode-proxy-agent\out\agent.js:4:12)
at _PacProxyAgent.callback (c:\Users\<user>\AppData\Local\Programs\Microsoft VS Code\resources\app\node_modules.asar\vscode-proxy-agent\out\agent.js:52:16)
at _PacProxyAgent.addRequest (c:\Users\<user>\AppData\Local\Programs\Microsoft VS Code\resources\app\node_modules.asar\vscode-proxy-agent\node_modules\agent-base\dist\src\index.js:184:38)
at new ClientRequest (node:_http_client:305:16)
at request (node:https:353:10)
at Object.patched (c:\Users\<user>\AppData\Local\Programs\Microsoft VS Code\resources\app\node_modules.asar\vscode-proxy-agent\out\index.js:298:24)
at Object.k.request.<computed>.k.request (c:\Users\<user>\.vscode\extensions\ms-vscode.azure-account-0.10.2-alpha\dist\extension.bundle.js:2:845291)
at Object.k.get (c:\Users\<user>\.vscode\extensions\ms-vscode.azure-account-0.10.2-alpha\dist\extension.bundle.js:2:845459)
at c:\Users\<user>\.vscode\extensions\ms-vscode.azure-account-0.10.2-alpha\dist\extension.bundle.js:2:2346057
at new Promise (<anonymous>)
at c:\Users\<user>\.vscode\extensions\ms-vscode.azure-account-0.10.2-alpha\dist\extension.bundle.js:2:2345930
at Generator.next (<anonymous>)
at c:\Users\<user>\.vscode\extensions\ms-vscode.azure-account-0.10.2-alpha\dist\extension.bundle.js:2:2345688
at new Promise (<anonymous>)
at b (c:\Users\<user>\.vscode\extensions\ms-vscode.azure-account-0.10.2-alpha\dist\extension.bundle.js:2:2345374)
at checkIsOnline (c:\Users\<user>\.vscode\extensions\ms-vscode.azure-account-0.10.2-alpha\dist\extension.bundle.js:2:2345879)
at c:\Users\<user>\.vscode\extensions\ms-vscode.azure-account-0.10.2-alpha\dist\extension.bundle.js:2:2346594
at Generator.next (<anonymous>)
at fulfilled (c:\Users\<user>\.vscode\extensions\ms-vscode.azure-account-0.10.2-alpha\dist\extension.bundle.js:2:2345442)
[2022-04-04 11:05:36.598] [exthost] [trace] ExtHostCommands#executeCommand setContext
[2022-04-04 11:05:36.598] [exthost] [trace] [DiagnosticCollection] change many (extension, owner, uris) msazurermtools.azurerm-vscode-tools azurerm-tools-expressions [[{"$mid":1,"fsPath":"extension-output-ms-vscode.azure-account-#1","_sep":1,"external":"output:extension-output-ms-vscode.azure-account-%231","path":"extension-output-ms-vscode.azure-account-#1","scheme":"output"},null]]
[2022-04-04 11:05:36.598] [exthost] [trace] ExtHostCommands#executeCommand setContext
[2022-04-04 11:05:36.598] [exthost] [trace] ExtHostCommands#executeCommand setContext
[2022-04-04 11:05:36.598] [exthost] [trace] ExtHostCommands#executeCommand setContext
[2022-04-04 11:05:41.061] [exthost] [debug] ProxyResolver#resolveProxy cached https://login.microsoftonline.com/ PROXY proxy.<fqdn>:80

**Comment by wwlorey** [comment]
@jamesorlando does this reproduce on any other machines that you have access to that are under the proxy?  This is very likely related to the specific configuration of your machine. Also, please try reinstalling VS Code.

**Comment by jamesorlando** [comment]
Yes, it is impacting most machines I have access to. I got one machine working by deleting all the expired certificates in the Current User store... However, I just met with another user and tried this unsuccessfully. 
I did try to wipe and reinstall, and it did not help.

**Comment by jamesorlando** [comment]
@wwlorey We are getting mixed results with cleaning up users expired certificates. Is there any way to get more information as to what certificate is expired? Some of my users need to hold on to expired certificates for previously encrypted email (Entrust), so they are hesitant to take the shotgun approach and delete every expired certificate from their systems. 

If we could get a thumbprint written to a log or something like that would be wildly helpful. Or is the extension just brining in every certificate and the fix is going to be to delete/export every expired certificate?

**Comment by jamesorlando** [comment]
Looks like we can resolve this issue by removing expired enterprise root and intermediate certificates from the Current User Store. You do have to restart VS Code as well after you do this.

**Comment by davidecavallari** [comment]
I had the same error. Under macOS, I solved by opening the Keychain Access app, selecting View > Show Expired Certificates, and deleting **all** certificates with **Expires** field before current date.
