### ISSUE TITLE
Azure account login fails from 0.9.11 onwards

### ISSUE THREAD

**Issue by yannchaput** [microsoft/vscode-azure-account#579]
Does this occur consistently? Yes
Repro steps:

1. Sign to Azure through Azure account login (v0.10.0)
2. Display Azure resources with Azure resources plugin

Action: azure-account.login
Error type: Error
Error Message: No response from the server
Wed, 08 Jun 2022 21:34:34 GMT:41d3a1f7-40c9-4a6b-a3fc-be50f295a973 - OAuth2Client: ERROR: No response from the server
Stack:
Error: No response from the server
	at Logger.createError (c:\Users\B065CD\.vscode\extensions\ms-vscode.azure-account-0.10.0\dist\extension.bundle.js:2:788524)
	at c:\Users\B065CD\.vscode\extensions\ms-vscode.azure-account-0.10.0\dist\extension.bundle.js:2:801557
	at runMicrotasks (<anonymous>)
	at processTicksAndRejections (node:internal/process/task_queues:96:5)
Error: No response from the server
Error: No response from the server

Version: 0.10.0
OS: win32
OS Release: 10.0.18363
Product: Visual Studio Code
Product Version: 1.67.2
Language: fr

<details>
<summary>Call Stack</summary>

```
Logger.createError extension.bundle.js:2:788524
extension.bundle.js:2:801557extension.bundle.js:2:801557
```

</details>

**Comment by yannchaput** [comment]
Like several people (https://github.com/microsoft/vscode-azure-account/issues/507) I have the issue above "No response from the server". The Azure Account window log shows this stacktrace: Wed, 08 Jun 2022 21:34:34 GMT:41d3a1f7-40c9-4a6b-a3fc-be50f295a973 - OAuth2Client: ERROR: No response from the server
Stack:
Error: No response from the server
	at Logger.createError (c:\Users\B065CD\.vscode\extensions\ms-vscode.azure-account-0.10.0\dist\extension.bundle.js:2:788524)
	at c:\Users\B065CD\.vscode\extensions\ms-vscode.azure-account-0.10.0\dist\extension.bundle.js:2:801557
	at runMicrotasks (<anonymous>)
	at processTicksAndRejections (node:internal/process/task_queues:96:5)
Error: No response from the server
Error: No response from the server

**Comment by yannchaput** [comment]
If I downgrade all Azure plugin to a 6 month old version, like 0.9.11 for Azure account it works. As soon as I upgrade to a version above, it fails with this error. I tested it with 0.10.0 and 0.10.1.

**Comment by alexweininger** [comment]
@yannchaput  we've created two development builds with proposed fixes for proxy issues. It would be a huge help if you could test these. #714 contains details and instructions on how to do so.
