### ISSUE TITLE
Change Azure Account Directory

### ISSUE THREAD

**Issue by chrriedel** [Microsoft/vscode-azure-account#58]
I am working as a Consultant at a Microsoft Consulting Company. We are MS CSP and therefore delegated admin for our cloud customers.
So I manage several customers with one azure portal account.

Is it possible to switch the azure directory in the azure account extension?

If not, this would be a great enhancement.

Cheers
Chris

**Comment by chrmarti** [comment]
When you login, you go through the login website and get redirected based on your email address. Does that not take care of using a different directory?

**Comment by chrmarti** [comment]
Do you have an endpoint URL for the directory you use? We could add a setting to override the default, that might then just work from what I see in the API.

**Comment by chrriedel** [comment]
I tested around a bit. I am able to switch the directory in the browser if I use this type of URL https://portal.azure.com/@contoso.com where contoso.com is the customers domain.

**Comment by chrmarti** [comment]
I might have overlooked the obvious. Could you try:
- Git-clone this repository to a local folder.
- `npm install`
- Open VS Code on the local folder.
- Change `'common'` to `'contoso.onmicrosoft.com'` in `src/azure-account.ts` line 45.
- `F5` to start a new VS Code window with the above change to the extension.
- Try signing in in the new window.

**Comment by chrriedel** [comment]
I am getting error while start debugging. 
C:\Program Files\Microsoft VS Code\Code.exe --debugBrkPluginHost=24324 --debugId=48094113-6518-4266-8c20-9a1f14ae0d66 --extensionDevelopmentPath=C:\DevProjects\vscode-azure-account 
Activating extension 'ms-vscode.azure-account' failed: Cannot find module 'C:\DevProjects\vscode-azure-account\out\src\extension'.
Activating extension `ms-vscode.azure-account` failed:  Cannot find module 'C:\DevProjects\vscode-azure-account\out\src\extension'
Here is the error stack:  Error: Cannot find module 'C:\DevProjects\vscode-azure-account\out\src\extension'
	at Function.Module._resolveFilename (module.js:470:15)
	at Function.Module._load (module.js:418:25)
	at Function.t.getExtensionPathIndex.then.o._load (c:\Program Files\Microsoft VS Code\resources\app\out\vs\workbench\node\extensionHostProcess.js:696:771)
	at Module.require (module.js:498:17)
	at Module.patchedRequire [as require] (c:\Program Files\Microsoft VS Code\resources\app\extensions\git\node_modules\diagnostic-channel\dist\src\patchRequire.js:14:46)
	at require (internal/module.js:20:19)
	at Function.i [as __$__nodeRequire] (c:\Program Files\Microsoft VS Code\resources\app\out\vs\loader.js:30:770)
	at c:\Program Files\Microsoft VS Code\resources\app\out\vs\workbench\node\extensionHostProcess.js:721:131
	at t._doActivateExtension (c:\Program Files\Microsoft VS Code\resources\app\out\vs\workbench\node\extensionHostProcess.js:721:243)
	at t._activateExtension (c:\Program Files\Microsoft VS Code\resources\app\out\vs\workbench\node\extensionHostProcess.js:720:161)
	at Object.actualActivateExtension (c:\Program Files\Microsoft VS Code\resources\app\out\vs\workbench\node\extensionHostProcess.js:718:48)
	at e._activateExtension (c:\Program Files\Microsoft VS Code\resources\app\out\vs\workbench\node\extensionHostProcess.js:428:188)
	at c:\Program Files\Microsoft VS Code\resources\app\out\vs\workbench\node\extensionHostProcess.js:427:757
	at Array.map (native)
	at e._activateExtensions (c:\Program Files\Microsoft VS Code\resources\app\out\vs\workbench\node\extensionHostProcess.js:427:732)
	at e._activateExtensions (c:\Program Files\Microsoft VS Code\resources\app\out\vs\workbench\node\extensionHostProcess.js:427:809)
	at e._activateExtensions (c:\Program Files\Microsoft VS Code\resources\app\out\vs\workbench\node\extensionHostProcess.js:427:809)
	at e.activateByEvent (c:\Program Files\Microsoft VS Code\resources\app\out\vs\workbench\node\extensionHostProcess.js:426:14)
	at t.activateByEvent (c:\Program Files\Microsoft VS Code\resources\app\out\vs\workbench\node\extensionHostProcess.js:718:412)
	at t.handleEagerExtensions (c:\Program Files\Microsoft VS Code\resources\app\out\vs\workbench\node\extensionHostProcess.js:740:885)
	at c:\Program Files\Microsoft VS Code\resources\app\out\vs\workbench\node\extensionHostProcess.js:740:79
	at Object.g [as _notify] (c:\Program Files\Microsoft VS Code\resources\app\out\vs\workbench\node\extensionHostProcess.js:69:572)
	at Object.enter (c:\Program Files\Microsoft VS Code\resources\app\out\vs\workbench\node\extensionHostProcess.js:72:924)
	at n.Class.derive._oncancel._run (c:\Program Files\Microsoft VS Code\resources\app\out\vs\workbench\node\extensionHostProcess.js:74:719)
	at n.Class.derive._oncancel._completed (c:\Program Files\Microsoft VS Code\resources\app\out\vs\workbench\node\extensionHostProcess.js:74:160)
	at e.open (c:\Program Files\Microsoft VS Code\resources\app\out\vs\workbench\node\extensionHostProcess.js:99:538)
	at c:\Program Files\Microsoft VS Code\resources\app\out\vs\workbench\node\extensionHostProcess.js:718:86
	at Object.g [as _notify] (c:\Program Files\Microsoft VS Code\resources\app\out\vs\workbench\node\extensionHostProcess.js:69:572)
	at Object.enter (c:\Program Files\Microsoft VS Code\resources\app\out\vs\workbench\node\extensionHostProcess.js:72:924)
	at n.Class.derive._oncancel._run (c:\Program Files\Microsoft VS Code\resources\app\out\vs\workbench\node\extensionHostProcess.js:74:719)
	at n.Class.derive._oncancel._completed (c:\Program Files\Microsoft VS Code\resources\app\out\vs\workbench\node\extensionHostProcess.js:74:160)
	at c (c:\Program Files\Microsoft VS Code\resources\app\out\vs\workbench\node\extensionHostProcess.js:77:654)
	at n.Class.derive.join.i.forEach.K.then.o.(anonymous function) (c:\Program Files\Microsoft VS Code\resources\app\out\vs\workbench\node\extensionHostProcess.js:77:868)
	at Object.g [as _notify] (c:\Program Files\Microsoft VS Code\resources\app\out\vs\workbench\node\extensionHostProcess.js:69:572)
	at Object.enter (c:\Program Files\Microsoft VS Code\resources\app\out\vs\workbench\node\extensionHostProcess.js:72:924)
	at n.Class.derive._oncancel._run (c:\Program Files\Microsoft VS Code\resources\app\out\vs\workbench\node\extensionHostProcess.js:74:719)
	at n.Class.derive._oncancel._completed (c:\Program Files\Microsoft VS Code\resources\app\out\vs\workbench\node\extensionHostProcess.js:74:160)
	at c:\Program Files\Microsoft VS Code\resources\app\out\vs\workbench\node\extensionHostProcess.js:103:447
	at c:\Program Files\Microsoft VS Code\resources\app\out\vs\workbench\node\extensionHostProcess.js:135:611
	at LOOP (fs.js:1728:14)
	at _combinedTickCallback (internal/process/next_tick.js:73:7)
	at process._tickCallback (internal/process/next_tick.js:104:9)
vscode-icons is active!
Extension 'ms-azuretools.vscode-azurestorage' failed to activate. Reason: dependency 'ms-vscode.azure-account' failed to activate.
Extension 'ms-azuretools.vscode-azureappservice' failed to activate. Reason: dependency 'ms-vscode.azure-account' failed to activate.
Extension 'ms-azuretools.vscode-azurefunctions' failed to activate. Reason: dependency 'ms-vscode.azure-account' failed to activate.
Extension 'bradygaster.azuretoolsforvscode' failed to activate. Reason: dependency 'ms-azuretools.vscode-azurestorage' failed to activate.

**Comment by chrmarti** [comment]
Which version of `tsc` have you installed? (`tsc --version`) Not sure if that could be the cause, it works for me with 2.7.2.

**Comment by gnerd** [comment]
i have the same issue - i have delegated rights to another person in my subscription. They can log into Azure portal fine, but when they do it via Code with the extension, it doesn't show the other subscription.

**Comment by chrmarti** [comment]
@gnerd That sounds like a different issue, unless the subscription belongs to another directory. Could you open a new issue to track it?

**Comment by chrmarti** [comment]
(Reopening because the setting is still hidden.)

There is a hidden setting you can set to the tenant you want to use: `"azure.tenant": "tenant.onmicrosoft.com"`. The settings editor will complain about not knowing the setting, that can be ignored.

Could give that a try? (Make sure you upgrade to 0.4.3 of the extension.)

**Comment by chrmarti** [comment]
@chrriedel @tobiaswi Did have time to give the new setting a try?

**Comment by tobiaswi** [comment]
@chrmarti Just tried it and it worked! Thank you so much, this makes my life a lot better now!

If I may request one more quality of life change:

If you could wrap this into a vscode command like ">Azure: Select Tenant" here:
![image](https://user-images.githubusercontent.com/15244405/43767213-cd447ec0-9a34-11e8-994d-457b2cbe3549.png)
It should check if the tenant i entered is different to the one im already logged in and if true, start the signin (vscode notification).

This would be very valuable to me as a CSP user as I switch tenants multiple times a day.

**Comment by chrmarti** [comment]
@tobiaswi Great, thanks for confirming! Just to better understand: Can you switch tenants when you change the setting and then just reload the window? (There is a command in the command palette 'Reload Window'.)

**Comment by tobiaswi** [comment]
@chrmarti Yes this works. There is some patience required.
1. Change settings, save and reload
2. Press F1 without waiting 5-10seconds after reload and call "Azure: Select Subscriptions"
3. Get the previous tenants subscription list.
4. Retry F1 + "Azure: Select Subscriptions"
5. New setting list is displayed

**Comment by bajorgensen** [comment]
+1 on this issue, even though there is a quirky workaround.
Native CSP support would be great as it seems like this extension is used by many other extensions.

**Comment by chrmarti** [comment]
Available in 0.5.0. It is no longer necessary to reload.

**Comment by chrriedel** [comment]
Sorry for not being responsive on that for a long time. I had some different stuff in between. I tested the 0.5.0 Version and it works great. 

+1 from me for the Azure:Select Tenant Command.

**Comment by chrmarti** [comment]
Thanks @chrriedel. I just opened https://github.com/Microsoft/vscode-azure-account/issues/101 to track the Select Tenant command.
