### ISSUE TITLE
Proxy support development builds

### ISSUE THREAD

**Issue by alexweininger** [microsoft/vscode-azure-account#714]
In an effort to fix issues related to signing in while using a proxy, we've created some development builds with potential fixes. We need help verifying these fixes. If you currently are facing issues signing in using the extension, and have a proxy configured, we could use your help testing our proposed solutions.

For now we've created two developments builds containing different proposed solutions (#710, #712). The extension versions for these are as follows:

1. axios: `0.11.4-alpha.1` #710
1. global-agent: `0.11.4-alpha.2` #712

[azure-account-proxy-development-builds.zip](https://github.com/microsoft/vscode-azure-account/files/10669787/azure-account-proxy-development-builds.zip)

---

#### Installing an extension development build
1. Download the zip containing development extension .VSIX [azure-account-proxy-development-builds.zip](https://github.com/microsoft/vscode-azure-account/files/10669787/azure-account-proxy-development-builds.zip)
1. From the command palette (`F1` or `Command/Ctrl + Shift + P`), run the "Extensions: Install from VSIX..." command.
1. Select the downloaded .VSIX file, then reload VS Code as prompted.

#### Testing

1. Remove `login.microsoftonline.com` from the `NO_PROXY` environment variable if present.
1. Install the development build using the steps outlined above.
1. Sign out of Azure completely using the "Azure: Sign Out" command from the palette.
1. Quit or close all VS Code windows.
1. Re-open VS Code and attempt to sign in to Azure.

After testing a development build please record the details and repeat the steps for the next proposed solution.

#### Reporting results

If you go through the above steps to install and test the proposed solutions, please report the results as a comment on this issue.

```md
## Environment information

VS Code version:
OS version:

Proxy configuration details (please redact private information as needed):
	* `HTTP_PROXY`:
	* `HTTPS_PROXY`:
	* `NO_PROXY`:
	* `http.proxy` VS Code setting:

## Details

### Proposed fix 1 - axios: `0.11.4-alpha.1`

Sign in succeed? **Yes/No**

If no, please provide any error messages or logs from the "Azure Account" Output Channel.

### Proposed fix 2 - global-agent: `0.11.4-alpha.2`

Sign in succeed? **Yes/No**

If no, please provide any error messages or logs from the "Azure Account" Output Channel.
```

Thank you!

**Comment by jg572h** [comment]
Here's what I get:

## Environment information

VS Code version: 1.75.0
OS version: Windows_NT x64 10.0.19042

Proxy configuration details (please redact private information as needed):
	* `HTTP_PROXY`: `<e-mail>:<proxy-PW>@<proxyURL>:8080`
	* `HTTPS_PROXY`: `<e-mail>:<proxy-PW>@<proxyURL>:8080`
	* `NO_PROXY`: `<Not set>`
	* `http.proxy` VS Code setting:  `<empty>`

## Details

### Proposed fix 1 - axios: `0.11.4-alpha.1`

Sign in succeed? **No**

If no, please provide any error messages or logs from the "Azure Account" Output Channel.

Attempting to reach URL "https://login.microsoftonline.com/"...
Attempting to reach URL "https://login.microsoftonline.com/"...
Attempting to reach URL "https://vscode.dev/redirect"...
Attempting to reach URL "https://login.microsoftonline.com/common/oauth2/authorize?response_type=code&client_id=aebc6443-996d-45c2-90f0-388ff96faa56&redirect_uri=https%3A%2F%2Fvscode.dev%2Fredirect&state=http%3A%2F%2F127.0.0.1%3A51741%2Fcallback?nonce=rxRX5l5C0KWgp5l93nrvOw%3D%3D&prompt=select_account"...
Tue, 07 Feb 2023 14:42:48 GMT:506cdc97-dd10-4250-8e62-c554511ba7e5 - OAuth2Client: ERROR: No response from the server
Stack:
Error: No response from the server
	at Logger.createError (c:\Users\jg572h\.vscode\extensions\ms-vscode.azure-account-0.11.4-alpha.1\dist\extension.bundle.js:2:865070)
	at c:\Users\jg572h\.vscode\extensions\ms-vscode.azure-account-0.11.4-alpha.1\dist\extension.bundle.js:2:878103
	at process.processTicksAndRejections (node:internal/process/task_queues:96:5)
Error: No response from the server
No response from the server

### Proposed fix 2 - global-agent: `0.11.4-alpha.2`

Sign in succeed? **No**

If no, please provide any error messages or logs from the "Azure Account" Output Channel.

Attempting to reach URL "https://login.microsoftonline.com/"...
Attempting to reach URL "https://login.microsoftonline.com/"...
Attempting to reach URL "https://login.microsoftonline.com/"...
Attempting to reach URL "https://login.microsoftonline.com/"...
Attempting to reach URL "https://login.microsoftonline.com/"...
Attempting to reach URL "https://login.microsoftonline.com/"...
Attempting to reach URL "https://login.microsoftonline.com/"...
Attempting to reach URL "https://login.microsoftonline.com/"...
Attempting to reach URL "https://login.microsoftonline.com/"...
Attempting to reach URL "https://login.microsoftonline.com/"...
Attempting to reach URL "https://login.microsoftonline.com/"...
Attempting to reach URL "https://login.microsoftonline.com/"...
Attempting to reach URL "https://login.microsoftonline.com/"...
Attempting to reach URL "https://login.microsoftonline.com/"...
Attempting to reach URL "https://login.microsoftonline.com/"...
Attempting to reach URL "https://login.microsoftonline.com/"...
Attempting to reach URL "https://login.microsoftonline.com/"...
Attempting to reach URL "https://login.microsoftonline.com/"...
Attempting to reach URL "https://login.microsoftonline.com/"...
Attempting to reach URL "https://login.microsoftonline.com/"...
Attempting to reach URL "https://login.microsoftonline.com/"...
Attempting to reach URL "https://login.microsoftonline.com/"...
Attempting to reach URL "https://login.microsoftonline.com/"...
Attempting to reach URL "https://login.microsoftonline.com/"...
Attempting to reach URL "https://login.microsoftonline.com/"...
Attempting to reach URL "https://login.microsoftonline.com/"...
Attempting to reach URL "https://login.microsoftonline.com/"...
Attempting to reach URL "https://login.microsoftonline.com/"...
Attempting to reach URL "https://login.microsoftonline.com/"...
Attempting to reach URL "https://login.microsoftonline.com/"...

(continues indefinitely)

## Other notes
In case this is important, when I open my workspace, I get the following error, as a pop-up in the lower-right corner:

HTTPS_PROXY environment variable ignored: Invalid URL
Source: Configuration Editing (Extension)

**Comment by alexweininger** [comment]
@jg572h thank you for taking the time to test out the builds and provide a detailed report.

**Comment by jg572h** [comment]
> @jg572h thank you for taking the time to test out the builds and provide a detailed report.

@alexweininger Sure thing.  I hope this provides some useful data.

**Comment by yannchaput** [comment]
## Environment information

VS Code version:
OS version:

Proxy configuration details (please redact private information as needed):
	* `HTTP_PROXY`: _http://127.0.0.1:5000_
	* `HTTPS_PROXY`: _http://127.0.0.1:5000_
	* `NO_PROXY`: _NA_
	* `http.proxy` VS Code setting: _empty (inherited from env variables above)_

## Details

### Proposed fix 1 - axios: `0.11.4-alpha.1`

Sign in succeed? **No**

If no, please provide any error messages or logs from the "Azure Account" Output Channel.

Attempting to reach URL "https://login.microsoftonline.com/"...
Attempting to reach URL "https://login.microsoftonline.com/"...
Attempting to reach URL "https://vscode.dev/redirect"...
Attempting to reach URL "https://login.microsoftonline.com/common/oauth2/authorize?response_type=code&client_id=aebc6443-996d-45c2-90f0-388ff96faa56&redirect_uri=https%3A%2F%2Fvscode.dev%2Fredirect&state=http%3A%2F%2F127.0.0.1%3A65319%2Fcallback?nonce=QEVctac0xK%2FJHMFuLfjHpw%3D%3D&prompt=select_account"...
Wed, 08 Feb 2023 09:31:01 GMT:13217876-a219-4bbb-bcfd-34ab6375d0c5 - OAuth2Client: ERROR: No response from the server
Stack:
Error: No response from the server
	at Logger.createError (c:\Users\B065CD\.vscode\extensions\ms-vscode.azure-account-0.11.4-alpha.1\dist\extension.bundle.js:2:865070)
	at c:\Users\B065CD\.vscode\extensions\ms-vscode.azure-account-0.11.4-alpha.1\dist\extension.bundle.js:2:878103
	at process.processTicksAndRejections (node:internal/process/task_queues:96:5)
Error: No response from the server
No response from the server


### Proposed fix 2 - global-agent: `0.11.4-alpha.2`

Sign in succeed? **No**

If no, please provide any error messages or logs from the "Azure Account" Output Channel.

Attempting to reach URL "https://login.microsoftonline.com/"...
Attempting to reach URL "https://login.microsoftonline.com/"...
Attempting to reach URL "https://vscode.dev/redirect"...
Attempting to reach URL "https://login.microsoftonline.com/common/oauth2/authorize?response_type=code&client_id=aebc6443-996d-45c2-90f0-388ff96faa56&redirect_uri=https%3A%2F%2Fvscode.dev%2Fredirect&state=http%3A%2F%2F127.0.0.1%3A65183%2Fcallback?nonce=ETvYw2laT1QFAC1k3qBQ5Q%3D%3D&prompt=select_account"...
Wed, 08 Feb 2023 09:29:37 GMT:81ead789-a416-41fa-8f6e-541c8c4ecbd5 - OAuth2Client: ERROR: No response from the server
Stack:
Error: No response from the server
	at Logger.createError (c:\Users\B065CD\.vscode\extensions\ms-vscode.azure-account-0.11.4-alpha.2\dist\extension.bundle.js:2:865070)
	at c:\Users\B065CD\.vscode\extensions\ms-vscode.azure-account-0.11.4-alpha.2\dist\extension.bundle.js:2:878103
	at process.processTicksAndRejections (node:internal/process/task_queues:96:5)
Error: No response from the server
No response from the server

**Comment by alexweininger** [comment]
@yannchaput thank you for taking the time to test out the builds and provide a detailed report.

Does adding `login.microsoftonline.com` to your `NO_PROXY` environment variable work for you? See the [Unable to Sign In While Using a Proxy section of our wiki](https://github.com/microsoft/vscode-azure-account/wiki/Troubleshooting#unable-to-sign-in-while-using-a-proxy) for more details on the workaround.

**Comment by yannchaput** [comment]
@alexweininger : thanks for the workaround. By adding a NO_PROXY environment and using version v0.11.4-alpha of Azure account, I have now a different error linked to MFA. 
Then I don't have access to Azure function or Azure webapp plugin.

`Attempting to reach URL "https://login.microsoftonline.com/"...
Attempting to reach URL "https://vscode.dev/redirect"...
Attempting to reach URL "https://login.microsoftonline.com/common/oauth2/authorize?response_type=code&client_id=aebc6443-996d-45c2-90f0-388ff96faa56&redirect_uri=https%3A%2F%2Fvscode.dev%2Fredirect&state=http%3A%2F%2F127.0.0.1%3A63260%2Fcallback?nonce=h6IYq2utX%2BWgmu%2BA93RRwg%3D%3D&prompt=select_account"...
Acquiring token with refresh token failed
Error: Get Token request returned http error: 400 and server response: {"error":"interaction_required","error_description":"AADSTS50076: Due to a configuration change made by your administrator, or because you moved to a new location, you must use multi-factor authentication to access '797f4846-ba00-4fd7-ba43-dac1f8f63013'.\r\nTrace ID: 018d0c7a-bcf5-45cd-b228-10825f491e00\r\nCorrelation ID: ed66392a-c4c6-4e34-b681-9924db2d021f\r\nTimestamp: 2023-02-09 12:59:01Z","error_codes":[50076],"timestamp":"2023-02-09 12:59:01Z","trace_id":"018d0c7a-bcf5-45cd-b228-10825f491e00","correlation_id":"ed66392a-c4c6-4e34-b681-9924db2d021f","error_uri":"https://login.microsoftonline.com/error?code=50076","suberror":"basic_action"}`

If I revert 'Azure function or Webapp' plugin back to older version (i.e 1.6.2), then I still have the error above, but I do see the plug(-in and have access to azure function features.
