### ISSUE TITLE
Unable to log in to Azure using ADAL

### ISSUE THREAD

**Issue by jgtellez1** [microsoft/vscode-azure-account#817]
Customer is unable to log into Azure when using ADAL. It works using MSAL, but the AzureML VS Code extension requires ADAL authentication.

Error:

```
2023-05-25 14:40:05.670 [info] MSAL: [Thu, 25 May 2023 18:40:05 GMT] : @azure/msal-node@1.14.6 : Info - getTokenCache called

2023-05-25 14:40:05.671 [trace] MSAL: [Thu, 25 May 2023 18:40:05 GMT] : @azure/msal-node@1.14.6 : Trace - getAllAccounts called

2023-05-25 14:40:05.674 [trace] MSAL: [Thu, 25 May 2023 18:40:05 GMT] : @azure/msal-node@1.14.6 : Trace - Retrieving all cache keys

2023-05-25 14:40:05.676 [trace] MSAL: [Thu, 25 May 2023 18:40:05 GMT] : @azure/msal-node@1.14.6 : Trace - Getting cache key-value store

2023-05-25 14:40:05.680 [info] Attempting to reach URL https://login.microsoftonline.com...

2023-05-25 14:40:06.816 [info] Attempting to reach URL https://vscode.dev/redirect...

2023-05-25 14:40:06.817 [info] Attempting to reach URL https://login.microsoftonline.com/common/oauth2/authorize?response_type=code&client_id=***&redirect_uri=https%3A%2F%2Fvscode.dev%2Fredirect&state=http%3A%2F%2F127.0.0.1%3A63124%2Fcallback?nonce=KsYXhn5YIj4%2BzM%2Bvs%2Fwe3A%3D%3D&prompt=select_account...

2023-05-25 14:40:09.824 [trace] ADAL: Authority: VERBOSE: Performing instance discovery

2023-05-25 14:40:09.825 [trace] ADAL: Authority: VERBOSE: Performing static instance discovery

2023-05-25 14:40:09.827 [trace] ADAL: Authority: VERBOSE: Authority validated via static instance discovery.

2023-05-25 14:40:09.830 [debug] ADAL: TokenRequest: INFO: Getting token with auth code.

2023-05-25 14:40:09.832 [info]

┌────── Axios Request POST https://login.microsoftonline.com/common/oauth2/token?api-version=1.0

   Headers (8):

   └ Accept-Charset: "utf-8"

   └ Content-Type: "application/x-www-form-urlencoded"

   └ client-request-id: "***"

   └ return-client-request-id: "true"

   └ x-client-CPU: "x64"

   └ x-client-OS: "win32"

   └ x-client-SKU: "Node"

   └ x-client-Ver: "0.2.3"

   Query parameters (6):

   └ client_id: "***"

   └ client_secret: ""

   └ code: "***"

   └ grant_type: "authorization_code"

   └ redirect_uri:[https://vscode.dev/redirect

   └ resource: https://management.core.windows.net/

   Proxy configuration: None

└───────────────────────────────────────────────────

2023-05-25 14:40:10.005 [error] Error: No response from the server

   at Logger.createError (c:\Users\***\.vscode\extensions\ms-vscode.azure-account-0.11.4-alpha.0\dist\extension.bundle.js:2:907486)

   at c:\Users\***\.vscode\extensions\ms-vscode.azure-account-0.11.4-alpha.0\dist\extension.bundle.js:2:920519

   at process.processTicksAndRejections (node:internal/process/task_queues:96:5)

2023-05-25 14:40:10.007 [error] No response from the server
```
- VS Code Version:
- Azure Account Extension Version: v011.4-alpha.0
- OS Version:

Are you connected to a proxy server? Yes, proxy is configured correctly on VSCode.

**Comment by alexweininger** [comment]
> Are you connected to a proxy server? Yes, proxy is configured correctly on VSCode.

Does this mean that the proxy is configured via the proxy settings in VS Code?

**Comment by jgtellez1** [comment]
@alexweininger yes, proxy settings are configured in VS code.

**Comment by puzzler10** [comment]
I have the same error, also behind a proxy. I have to log in via MSAL (ADAL doesn't work) but this seems to break something when connecting to a compute instance with Azure ML. Wondering if there is any fixes. 

In the logs I am seeing a lot of messages like 

```
[Error - 2024-06-20 10:47:46.022] Failed to get user object id for the user xxx
```
and 
```
[Error - 2024-06-20 10:47:47.020] Error: Error obtaining refresh token for your subscription. Please try again
```
and 
```
[Error - 2024-06-20 10:46:03.655] Error: Cannot get password
```

**Comment by shsuman** [comment]
@puzzler10 What is the version of VS Code and Azure ML extension that you are using ?

**Comment by puzzler10** [comment]
Azure ML extension - v0.24.0
Azure ML Remote extension - v0.22.0
Azure Account extension - v0.11.3
VS Code - 1.70.2

**Comment by shsuman** [comment]
@puzzler10 Please update the Azure ML and Azure ML - Remote extension to latest version (0.48.0). You will need VS Code version 1.86.0 or above to do that. I recommend installing latest stable VS Code version (1.90.2)

**Comment by shsuman** [comment]
@alexweininger I think we can close this issue now :)

**Comment by alexweininger** [comment]
Thank you @shsuman!
