### ISSUE TITLE
Cannot able to sign in to azure account from visual studio code

### ISSUE THREAD

**Issue by satyakirank** [Microsoft/vscode-azure-account#85]
Im getting this error when trying to sign in azure account from vs code
**Error: getaddrinfo EAI_AGAIN login.microsoftonline.com:443**
at Object.exports._errnoException (util.js:1050:11)
at errnoException (dns.js:33:15)
at GetAddrInfoReqWrap.onlookup [as oncomplete] (dns.js:73:26)
**console.ts:136 [Extension Host] Error: Acquiring user code failed**
at C:\Users\durgavenkata.neeli.vscode\extensions\ms-vscode.azure-account-0.4.3\out\src\azure-account.js:550:28
at Request._callback (C:\Users\durgavenkata.neeli.vscode\extensions\ms-vscode.azure-account-0.4.3\node_modules\adal-node\lib\util.js:119:7)
at self.callback (C:\Users\durgavenkata.neeli.vscode\extensions\ms-vscode.azure-account-0.4.3\node_modules\request\request.js:186:22)
at emitOne (events.js:96:13)
at Request.emit (events.js:191:7)
at Request.onRequestError (C:\Users\durgavenkata.neeli.vscode\extensions\ms-vscode.azure-account-0.4.3\node_modules\request\request.js:878:8)
at emitOne (events.js:96:13)
at ClientRequest.emit (events.js:191:7)
at TLSSocket.socketErrorListener (_http_client.js:358:9)
at emitOne (events.js:96:13)
at TLSSocket.emit (events.js:191:7)
at connectErrorNT (net.js:1032:8)
at _combinedTickCallback (internal/process/next_tick.js:80:11)
at process._tickCallback (internal/process/next_tick.js:104:9)**

**Comment by chrmarti** [comment]
Does this still occur? What do you get for `nslookup login.microsoftonline.com ` when it fails?
