### ISSUE TITLE
Azure account login via docker extension fails

### ISSUE THREAD

**Issue by shishirb-MSFT** [microsoft/vscode-azure-account#865]
Does this occur consistently? YES
Repro steps:
1. Open VSCode
2. Open the Docker extension > Registries
3. Azure shows up already as a connected registry, with the expected subscription shown.
4. Expand the subscription item.
5. Expectation: Available registries in the azure subscription shown.
6. Actual: "Error. Your VS Code window must be reloaded to perform this action."
7. Restarting VSCode does not help. I also confirmed there is enough free memory (over 40GB available).

Action: azure-account.initialize
Error type: Error
Error Message: Not enough memory resources are available to process this command.

More logs:
2023-10-03 13:47:29.531 [info] Attempting to reach URL "https://login.microsoftonline.com/"...
2023-10-03 13:47:30.210 [info] MSAL: [Tue, 03 Oct 2023 20:47:30 GMT] : @azure/msal-node@1.14.6 : Info - getTokenCache called
2023-10-03 13:47:30.762 [info] Error: Not enough memory resources are available to process this command.

2023-10-03 13:48:19.660 [error] Error: Entry not found in cache.
    at Logger.createError (c:\Users\shishirb\.vscode\extensions\ms-vscode.azure-account-0.11.5\dist\extension.bundle.js:2:917183)
    at TokenRequest.<anonymous> (c:\Users\shishirb\.vscode\extensions\ms-vscode.azure-account-0.11.5\dist\extension.bundle.js:2:942619)
    at c:\Users\shishirb\.vscode\extensions\ms-vscode.azure-account-0.11.5\dist\extension.bundle.js:2:936969
    at c:\Users\shishirb\.vscode\extensions\ms-vscode.azure-account-0.11.5\dist\extension.bundle.js:2:909300
    at c:\Users\shishirb\.vscode\extensions\ms-vscode.azure-account-0.11.5\dist\extension.bundle.js:2:907628
    at c:\Users\shishirb\.vscode\extensions\ms-vscode.azure-account-0.11.5\dist\extension.bundle.js:2:906739
    at MemoryCache.find (c:\Users\shishirb\.vscode\extensions\ms-vscode.azure-account-0.11.5\dist\extension.bundle.js:2:917810)
    at c:\Users\shishirb\.vscode\extensions\ms-vscode.azure-account-0.11.5\dist\extension.bundle.js:2:2556106

Version: 0.11.5
OS: win32
OS Release: 10.0.22621
Product: Visual Studio Code
Product Version: 1.82.3
Language: en

**Comment by shishirb-MSFT** [comment]
The issue went away after VSCode updated to 1.83.0 ¯\_(ツ)_/¯
